/**
 * AUTOGENERATED — DO NOT EDIT.
 * Regenerated by scripts/build-catalogs.ts from data/*.yaml.
 */

import type { BourbonCardDef } from "./types";

export const BOURBON_CARDS: readonly BourbonCardDef[] = [
  {
    "id": "01",
    "name": "Knob's End 90",
    "rarity": "Standard",
    "grid": [
      [
        5,
        9
      ]
    ],
    "awards": null,
    "ageBands": [
      2
    ],
    "demandBands": [
      0,
      6
    ],
    "tier": "common",
    "slogan": "Last knob in the rack.",
    "description": "Bottled barrel-proof, sold at 90. The end of a long dump day."
  },
  {
    "id": "02",
    "name": "Mammoth Cave Malt",
    "rarity": "Standard",
    "grid": [
      [
        6,
        10
      ]
    ],
    "awards": null,
    "ageBands": [
      2
    ],
    "demandBands": [
      0,
      6
    ],
    "tier": "common",
    "slogan": "Aged in the dark.",
    "description": "Limestone water, malted barley, and one very large echo."
  },
  {
    "id": "03",
    "name": "Bardstown Boiler",
    "rarity": "Standard",
    "grid": [
      [
        9,
        11
      ]
    ],
    "awards": null,
    "ageBands": [
      2
    ],
    "demandBands": [
      0,
      6
    ],
    "tier": "common",
    "slogan": "Where the steam never sleeps.",
    "description": "Bardstown's main street, bottled. Workhorse pour at weeknight pricing."
  },
  {
    "id": "04",
    "name": "Limestone Ledger",
    "rarity": "Standard",
    "grid": [
      [
        5,
        9
      ]
    ],
    "awards": null,
    "ageBands": [
      2
    ],
    "demandBands": [
      0,
      6
    ],
    "tier": "common",
    "slogan": "Filtered through Kentucky.",
    "description": "Hard water, soft mouthfeel, accountant's clarity. Pays out exactly as advertised."
  },
  {
    "id": "05",
    "name": "Charred Oak Exchange",
    "rarity": "Standard",
    "grid": [
      [
        6,
        11
      ],
      [
        11,
        20
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      6
    ],
    "demandBands": [
      0,
      7
    ],
    "tier": "uncommon",
    "slogan": "Trade in the burn.",
    "description": "A blender's standby — char level four, vanilla up front, tannin on the back."
  },
  {
    "id": "06",
    "name": "Riverbend Rye Signal",
    "rarity": "Standard",
    "grid": [
      [
        9,
        13
      ],
      [
        13,
        21
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      6
    ],
    "demandBands": [
      0,
      7
    ],
    "tier": "uncommon",
    "slogan": "When the rye whistles, drink.",
    "description": "Spicy rye-forward bend with a citrus undercurrent. Reads the river before the sale."
  },
  {
    "id": "07",
    "name": "Stave & Story",
    "rarity": "Standard",
    "grid": [
      [
        5,
        10
      ],
      [
        10,
        18
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      6
    ],
    "demandBands": [
      0,
      7
    ],
    "tier": "uncommon",
    "slogan": "One barrel, one tale.",
    "description": "Each stave numbered, each pour narrated. Sells well to people who like provenance."
  },
  {
    "id": "08",
    "name": "Cooper's Quorum",
    "rarity": "Standard",
    "grid": [
      [
        9,
        11,
        16
      ],
      [
        11,
        16,
        23
      ],
      [
        16,
        25,
        33
      ]
    ],
    "awards": {
      "silver": "Sell at demand **≥5** **and** mash satisfies the bill recipe."
    },
    "ageBands": [
      2,
      5,
      8
    ],
    "demandBands": [
      0,
      5,
      8
    ],
    "tier": "rare",
    "recipe": {
      "barley": {
        "min": 1
      },
      "rye": {
        "min": 1
      },
      "wheat": {
        "min": 1
      }
    },
    "slogan": "Five staves agreed.",
    "description": "Built by hand, voted on by committee. The cooperage's house pour."
  },
  {
    "id": "09",
    "name": "Mash Bill No. 7",
    "rarity": "Standard",
    "grid": [
      [
        18,
        21,
        25
      ],
      [
        21,
        28,
        34
      ],
      [
        26,
        34,
        43
      ]
    ],
    "awards": {
      "silver": "Barrel **≥7 years** **and** sell at demand **≥6** **and** mash satisfies the recipe.",
      "gold": "Barrel **≥10 years** **and** demand **≥8** at sale **and** mash satisfies the recipe (grid **maximum** **$26**)."
    },
    "ageBands": [
      4,
      7,
      10
    ],
    "demandBands": [
      4,
      6,
      8
    ],
    "tier": "epic",
    "recipe": {
      "rye": {
        "min": 2
      },
      "wheat": {
        "min": 1
      }
    },
    "slogan": "Lucky number, regular price.",
    "description": "Reliable corn-rye-malt at 70/20/10. The seventh recipe, the first they kept.",
    "brandValue": 50
  },
  {
    "id": "10",
    "name": "High Rickhouse Select",
    "rarity": "Standard",
    "grid": [
      [
        25,
        41,
        58
      ],
      [
        33,
        58,
        81
      ],
      [
        49,
        81,
        114
      ]
    ],
    "awards": {
      "silver": "Barrel **≥10 years** **and** demand **≥7** at sale **and** mash satisfies the recipe.",
      "gold": "Barrel **≥15 years** **and** demand **≥10** at sale **and** mash uses **≥4 grain cards** with a specialty cask (grid **maximum** **$70**)."
    },
    "ageBands": [
      8,
      10,
      15
    ],
    "demandBands": [
      4,
      7,
      10
    ],
    "tier": "legendary",
    "recipe": {
      "grain": {
        "min": 4
      },
      "rye": {
        "min": 1
      },
      "wheat": {
        "min": 1
      }
    },
    "slogan": "Top of the rack, top of the bill.",
    "description": "Pulled from the seventh story. Hotter summers, faster aging, premium ask.",
    "brandValue": 120
  },
  {
    "id": "11",
    "name": "Warehouse E Batch",
    "rarity": "Standard",
    "grid": [
      [
        6,
        10
      ]
    ],
    "awards": null,
    "ageBands": [
      2
    ],
    "demandBands": [
      0,
      6
    ],
    "tier": "common",
    "slogan": "E for excellent. Or extra.",
    "description": "Whatever the rickhouse manager grabbed last. Consistent enough to bottle a label."
  },
  {
    "id": "12",
    "name": "Foggy Bottom Forge",
    "rarity": "Standard",
    "grid": [
      [
        9,
        11
      ]
    ],
    "awards": null,
    "ageBands": [
      2
    ],
    "demandBands": [
      0,
      6
    ],
    "tier": "common",
    "slogan": "Distilled in the river fog.",
    "description": "Bottled when the cooper couldn't see the next building. Tastes like the morning after."
  },
  {
    "id": "13",
    "name": "Cornbread Line",
    "rarity": "Standard",
    "grid": [
      [
        5,
        9
      ]
    ],
    "awards": null,
    "ageBands": [
      2
    ],
    "demandBands": [
      0,
      6
    ],
    "tier": "common",
    "slogan": "Sweet, hot, simple.",
    "description": "Eighty percent corn, twenty percent everything else. Pairs with most porches."
  },
  {
    "id": "14",
    "name": "Rye Ladder 95",
    "rarity": "Standard",
    "grid": [
      [
        6,
        11
      ],
      [
        11,
        20
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      6
    ],
    "demandBands": [
      0,
      7
    ],
    "tier": "uncommon",
    "slogan": "Climb to the spice.",
    "description": "Ninety-five percent rye — pepper, mint, and a long ladder down the throat."
  },
  {
    "id": "15",
    "name": "Wheat Whisper",
    "rarity": "Standard",
    "grid": [
      [
        9,
        13
      ],
      [
        13,
        21
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      6
    ],
    "demandBands": [
      0,
      7
    ],
    "tier": "uncommon",
    "slogan": "Soft, slow, certain.",
    "description": "Wheated mash bill that doesn't argue. Says what it means and means what it sips."
  },
  {
    "id": "16",
    "name": "Barley Bastion",
    "rarity": "Standard",
    "grid": [
      [
        5,
        10
      ],
      [
        10,
        18
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      6
    ],
    "demandBands": [
      0,
      7
    ],
    "tier": "uncommon",
    "slogan": "Holding the malt line.",
    "description": "Barley-heavy pot still that refuses to be subtle. Smoky, biscuit-y, decisive."
  },
  {
    "id": "17",
    "name": "Two Charring Points",
    "rarity": "Standard",
    "grid": [
      [
        9,
        11,
        16
      ],
      [
        11,
        16,
        23
      ],
      [
        16,
        25,
        33
      ]
    ],
    "awards": {
      "silver": "Sell at demand **≥5** **and** mash satisfies the bill recipe."
    },
    "ageBands": [
      2,
      5,
      8
    ],
    "demandBands": [
      0,
      5,
      8
    ],
    "tier": "rare",
    "recipe": {
      "rye": {
        "min": 2
      }
    },
    "slogan": "Twice toasted, never burnt.",
    "description": "Char two on the staves, char three on the heads. Caramelized either way."
  },
  {
    "id": "18",
    "name": "Angel's Trace",
    "rarity": "Standard",
    "grid": [
      [
        10,
        13,
        18
      ],
      [
        13,
        18,
        25
      ],
      [
        18,
        26,
        34
      ]
    ],
    "awards": {
      "silver": "Sell at demand **≥5** **and** mash satisfies the bill recipe."
    },
    "ageBands": [
      2,
      5,
      8
    ],
    "demandBands": [
      0,
      5,
      8
    ],
    "tier": "rare",
    "recipe": {
      "rye": {
        "min": 2
      }
    },
    "slogan": "What evaporated, signed in.",
    "description": "The barrel left a watermark in the air. The bottle preserves what was almost lost."
  },
  {
    "id": "19",
    "name": "Bonded & Bold",
    "rarity": "Standard",
    "grid": [
      [
        15,
        18,
        21
      ],
      [
        18,
        25,
        31
      ],
      [
        23,
        31,
        39
      ]
    ],
    "awards": {
      "silver": "Barrel **≥7 years** **and** sell at demand **≥6** **and** mash satisfies the recipe.",
      "gold": "Barrel **≥10 years** **and** demand **≥8** at sale **and** mash satisfies the recipe (grid **maximum** **$24**)."
    },
    "ageBands": [
      4,
      7,
      10
    ],
    "demandBands": [
      4,
      6,
      8
    ],
    "tier": "epic",
    "recipe": {
      "rye": {
        "min": 2
      },
      "wheat": {
        "min": 1
      }
    },
    "slogan": "Four years, one distillery, one season.",
    "description": "Bottled-in-bond, hundred proof, no compromise. Federally bossy, deliciously honest.",
    "brandValue": 45
  },
  {
    "id": "20",
    "name": "Cork & Crown",
    "rarity": "Standard",
    "grid": [
      [
        6,
        10
      ]
    ],
    "awards": null,
    "ageBands": [
      2
    ],
    "demandBands": [
      0,
      6
    ],
    "tier": "common",
    "slogan": "Sealed with intent.",
    "description": "Crown over Kentucky cork — table-side bourbon for people who like a little ceremony."
  },
  {
    "id": "21",
    "name": "Proof Positive 100",
    "rarity": "Standard",
    "grid": [
      [
        9,
        11
      ]
    ],
    "awards": null,
    "ageBands": [
      2
    ],
    "demandBands": [
      0,
      6
    ],
    "tier": "common",
    "slogan": "A century in a glass.",
    "description": "Hundred proof, hundred percent confident. The expression that audits itself."
  },
  {
    "id": "22",
    "name": "Sour Mash Society",
    "rarity": "Standard",
    "grid": [
      [
        5,
        9
      ]
    ],
    "awards": null,
    "ageBands": [
      2
    ],
    "demandBands": [
      0,
      6
    ],
    "tier": "common",
    "slogan": "Membership, one barrel.",
    "description": "Backset starter, multi-batch consistency. The same yeast strain since the first run."
  },
  {
    "id": "23",
    "name": "Stillhouse Sonnet",
    "rarity": "Standard",
    "grid": [
      [
        6,
        10
      ]
    ],
    "awards": null,
    "ageBands": [
      2
    ],
    "demandBands": [
      0,
      6
    ],
    "tier": "common",
    "slogan": "Fourteen lines of distillate.",
    "description": "Slow strip, slower spirit. Lyrical mouthfeel for the contemplative pour."
  },
  {
    "id": "24",
    "name": "Patent Still 04",
    "rarity": "Standard",
    "grid": [
      [
        9,
        13
      ],
      [
        13,
        21
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      6
    ],
    "demandBands": [
      0,
      7
    ],
    "tier": "uncommon",
    "slogan": "Column-built, hand-finished.",
    "description": "Continuous distillation that never broke a sweat. Number four in the rotation, first in efficiency."
  },
  {
    "id": "25",
    "name": "Kentucky Crosscut",
    "rarity": "Standard",
    "grid": [
      [
        5,
        10
      ],
      [
        10,
        18
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      6
    ],
    "demandBands": [
      0,
      7
    ],
    "tier": "uncommon",
    "slogan": "Cut against the grain.",
    "description": "Saws the difference between high-rye and high-corn. A blender's secret weapon."
  },
  {
    "id": "26",
    "name": "Oak Algebra",
    "rarity": "Standard",
    "grid": [
      [
        6,
        11
      ],
      [
        11,
        20
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      6
    ],
    "demandBands": [
      0,
      7
    ],
    "tier": "uncommon",
    "slogan": "Solve for time.",
    "description": "Years × surface area = flavor. We did the work; you taste the answer."
  },
  {
    "id": "27",
    "name": "Bottled Lightning 86",
    "rarity": "Standard",
    "grid": [
      [
        10,
        13,
        18
      ],
      [
        13,
        18,
        25
      ],
      [
        18,
        26,
        34
      ]
    ],
    "awards": {
      "silver": "Sell at demand **≥5** **and** mash satisfies the bill recipe."
    },
    "ageBands": [
      2,
      5,
      8
    ],
    "demandBands": [
      0,
      5,
      8
    ],
    "recipe": {
      "rye": {
        "min": 2
      }
    },
    "tier": "rare",
    "slogan": "Eighty-six proof, no warning.",
    "description": "The 1986 batch that got loose. Bright, hot, slightly afraid of itself."
  },
  {
    "id": "28",
    "name": "Copper Trace",
    "rarity": "Standard",
    "grid": [
      [
        15,
        18,
        21
      ],
      [
        18,
        25,
        31
      ],
      [
        23,
        31,
        39
      ]
    ],
    "awards": {
      "silver": "Barrel **≥7 years** **and** sell at demand **≥6** **and** mash satisfies the recipe.",
      "gold": "Barrel **≥10 years** **and** demand **≥8** at sale **and** mash satisfies the recipe (grid **maximum** **$24**)."
    },
    "ageBands": [
      4,
      7,
      10
    ],
    "demandBands": [
      4,
      6,
      8
    ],
    "recipe": {
      "rye": {
        "min": 2
      },
      "wheat": {
        "min": 1
      }
    },
    "tier": "epic",
    "slogan": "Distilled through the still's memory.",
    "description": "Pot still residue carries forward; this expression honors the lineage in micrograms.",
    "brandValue": 45
  },
  {
    "id": "29",
    "name": "Bluegrass Boiler",
    "rarity": "Standard",
    "grid": [
      [
        6,
        10
      ]
    ],
    "awards": null,
    "ageBands": [
      2
    ],
    "demandBands": [
      0,
      6
    ],
    "tier": "common",
    "slogan": "Bottled where the music plays.",
    "description": "Distilled in earshot of three festivals a year. Spirited, slightly off-tempo, very listenable."
  },
  {
    "id": "30",
    "name": "Rickhouse Arithmetic",
    "rarity": "Standard",
    "grid": [
      [
        9,
        11
      ]
    ],
    "awards": null,
    "ageBands": [
      2
    ],
    "demandBands": [
      0,
      6
    ],
    "tier": "common",
    "slogan": "Floors, years, dollars — sum it.",
    "description": "Floor seven, year nine, sale price elsewhere. The math that built the brand."
  },
  {
    "id": "31",
    "name": "Filtered Lore",
    "rarity": "Standard",
    "grid": [
      [
        5,
        9
      ]
    ],
    "awards": null,
    "ageBands": [
      2
    ],
    "demandBands": [
      0,
      6
    ],
    "tier": "common",
    "slogan": "Strain truth from rumor.",
    "description": "Charcoal-mellowed Lincoln-county style. The story stays; the harshness doesn't."
  },
  {
    "id": "32",
    "name": "Low Gauge Legacy",
    "rarity": "Standard",
    "grid": [
      [
        6,
        10
      ]
    ],
    "awards": null,
    "ageBands": [
      2
    ],
    "demandBands": [
      0,
      6
    ],
    "tier": "common",
    "slogan": "Cut at the lowest legal proof.",
    "description": "Entered the barrel at 110, came out at less. Patient distilling, generous pour."
  },
  {
    "id": "33",
    "name": "Steam Furnace Five",
    "rarity": "Standard",
    "grid": [
      [
        9,
        13
      ],
      [
        13,
        21
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      6
    ],
    "demandBands": [
      0,
      7
    ],
    "tier": "uncommon",
    "slogan": "Five furnaces, one fire.",
    "description": "Steam-heated cooker bank, batch number five. Cooks hot, sells warmer."
  },
  {
    "id": "34",
    "name": "Grist Galaxy",
    "rarity": "Standard",
    "grid": [
      [
        5,
        10
      ],
      [
        10,
        18
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      6
    ],
    "demandBands": [
      0,
      7
    ],
    "tier": "uncommon",
    "slogan": "Nine grains, one nebula.",
    "description": "Multi-grain mash that reads like an astronomy chart. Heavy bottle, dense flavor, infinite finish."
  },
  {
    "id": "35",
    "name": "Turf & Tarnish",
    "rarity": "Standard",
    "grid": [
      [
        6,
        11
      ],
      [
        11,
        20
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      6
    ],
    "demandBands": [
      0,
      7
    ],
    "tier": "uncommon",
    "slogan": "Polished by the field.",
    "description": "Earthy on entry, mineral on the way out. The bottle they keep behind the bar for the regulars."
  },
  {
    "id": "36",
    "name": "Copper Crossings 107",
    "rarity": "Rare",
    "grid": [
      [
        10,
        13,
        18
      ],
      [
        13,
        18,
        25
      ],
      [
        18,
        26,
        34
      ]
    ],
    "awards": {
      "silver": "Sell at demand **≥5** **and** mash satisfies the bill recipe."
    },
    "ageBands": [
      2,
      5,
      8
    ],
    "demandBands": [
      0,
      5,
      8
    ],
    "recipe": {
      "rye": {
        "min": 2
      }
    },
    "tier": "rare",
    "slogan": "Where the still meets the spirit.",
    "description": "Cask strength 107 proof. Three-still serial blend with copper notes throughout."
  },
  {
    "id": "37",
    "name": "Seven Stars Odd Lot",
    "rarity": "Rare",
    "grid": [
      [
        15,
        18,
        21
      ],
      [
        18,
        25,
        31
      ],
      [
        23,
        31,
        39
      ]
    ],
    "awards": {
      "silver": "Barrel **≥7 years** **and** sell at demand **≥6** **and** mash satisfies the recipe.",
      "gold": "Barrel **≥10 years** **and** demand **≥8** at sale **and** mash satisfies the recipe (grid **maximum** **$24**)."
    },
    "ageBands": [
      4,
      7,
      10
    ],
    "demandBands": [
      4,
      6,
      8
    ],
    "tier": "epic",
    "recipe": {
      "rye": {
        "min": 2
      },
      "wheat": {
        "min": 1
      }
    },
    "slogan": "Seven barrels, not one matches.",
    "description": "An accidental small-batch from seven mismatched racks. Better than the recipe.",
    "brandValue": 50
  },
  {
    "id": "38",
    "name": "State Line BiB",
    "rarity": "Rare",
    "grid": [
      [
        28,
        44,
        60
      ],
      [
        36,
        60,
        85
      ],
      [
        53,
        85,
        118
      ]
    ],
    "awards": {
      "silver": "Barrel **≥10 years** **and** demand **≥7** at sale **and** mash satisfies the recipe.",
      "gold": "Barrel **≥15 years** **and** demand **≥10** at sale **and** mash uses **≥4 grain cards** with a specialty cask (grid **maximum** **$72**)."
    },
    "ageBands": [
      8,
      10,
      15
    ],
    "demandBands": [
      4,
      7,
      10
    ],
    "tier": "legendary",
    "recipe": {
      "grain": {
        "min": 4
      },
      "rye": {
        "min": 1
      },
      "wheat": {
        "min": 1
      }
    },
    "slogan": "Bottled-in-bond, distilled-on-the-line.",
    "description": "Straddles the Kentucky-Tennessee line. Bottled-in-bond, regulated to a fault, blessed by both auditors.",
    "brandValue": 130
  },
  {
    "id": "39",
    "name": "Barrel Thief Reserve",
    "rarity": "Rare",
    "grid": [
      [
        9,
        11
      ]
    ],
    "awards": null,
    "ageBands": [
      2
    ],
    "demandBands": [
      0,
      6
    ],
    "tier": "common",
    "slogan": "Stolen straight from the bung.",
    "description": "Bottled at the moment the warehouse manager dipped the thief. Unfiltered honesty."
  },
  {
    "id": "40",
    "name": "Ghost Warehouse",
    "rarity": "Rare",
    "grid": [
      [
        5,
        9
      ]
    ],
    "awards": null,
    "ageBands": [
      2
    ],
    "demandBands": [
      0,
      6
    ],
    "tier": "common",
    "slogan": "We forgot it was here.",
    "description": "Found in a sealed rickhouse during inventory. Eighteen years undocumented, fully aged, mostly evaporated."
  },
  {
    "id": "41",
    "name": "Double Stack Destiny",
    "rarity": "Rare",
    "grid": [
      [
        6,
        10
      ]
    ],
    "awards": null,
    "ageBands": [
      2
    ],
    "demandBands": [
      0,
      6
    ],
    "tier": "common",
    "slogan": "Two ricks, one fate.",
    "description": "Aged in two adjacent rickhouses simultaneously. Microclimate split that nobody can reproduce."
  },
  {
    "id": "42",
    "name": "Crimson Corn Covenant",
    "rarity": "Rare",
    "grid": [
      [
        9,
        13
      ],
      [
        13,
        21
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      6
    ],
    "demandBands": [
      0,
      7
    ],
    "tier": "uncommon",
    "slogan": "Heirloom corn, holy water.",
    "description": "Bloody Butcher dent corn — the kind your grandfather grew. Tastes like a promise."
  },
  {
    "id": "43",
    "name": "Platinum Rick Proof",
    "rarity": "Rare",
    "grid": [
      [
        5,
        10
      ],
      [
        10,
        18
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      6
    ],
    "demandBands": [
      0,
      7
    ],
    "tier": "uncommon",
    "slogan": "Cask strength, monocle optional.",
    "description": "The expression for the boardroom. Cask strength, single rick, signed by the master distiller."
  },
  {
    "id": "44",
    "name": "Infinite Stave",
    "rarity": "Rare",
    "grid": [
      [
        6,
        11
      ],
      [
        11,
        20
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      6
    ],
    "demandBands": [
      0,
      7
    ],
    "tier": "uncommon",
    "slogan": "Aged forever, by definition.",
    "description": "Solera-method bourbon: every bottle contains some of the first. Mathematically immortal."
  },
  {
    "id": "45",
    "name": "Crown Compass",
    "rarity": "Rare",
    "grid": [
      [
        10,
        13,
        18
      ],
      [
        13,
        18,
        25
      ],
      [
        18,
        26,
        34
      ]
    ],
    "awards": {
      "silver": "Sell at demand **≥5** **and** mash satisfies the bill recipe."
    },
    "ageBands": [
      2,
      5,
      8
    ],
    "demandBands": [
      0,
      5,
      8
    ],
    "recipe": {
      "rye": {
        "min": 2
      }
    },
    "tier": "rare",
    "slogan": "True north, true proof.",
    "description": "Navigated by demand. The bottle that always points to the highest price."
  },
  {
    "id": "46",
    "name": "Ledger Luxe",
    "rarity": "Rare",
    "grid": [
      [
        6,
        10,
        15
      ],
      [
        10,
        15,
        21
      ],
      [
        15,
        23,
        31
      ]
    ],
    "awards": {
      "silver": "Sell at demand **≥5** **and** mash satisfies the bill recipe."
    },
    "ageBands": [
      2,
      5,
      8
    ],
    "demandBands": [
      0,
      5,
      8
    ],
    "recipe": {
      "rye": {
        "min": 2
      }
    },
    "tier": "rare",
    "slogan": "The premium line, audited.",
    "description": "Distilled for collectors who want a paper trail. Provenance, proof, and a foil seal."
  },
  {
    "id": "47",
    "name": "Wild Rickhouse",
    "rarity": "Rare",
    "grid": [
      [
        16,
        20,
        23
      ],
      [
        20,
        26,
        33
      ],
      [
        25,
        33,
        41
      ]
    ],
    "awards": {
      "silver": "Barrel **≥7 years** **and** sell at demand **≥6** **and** mash satisfies the recipe.",
      "gold": "Barrel **≥10 years** **and** demand **≥8** at sale **and** mash satisfies the recipe (grid **maximum** **$25**)."
    },
    "ageBands": [
      4,
      7,
      10
    ],
    "demandBands": [
      4,
      6,
      8
    ],
    "tier": "epic",
    "recipe": {
      "rye": {
        "min": 2
      },
      "wheat": {
        "min": 1
      }
    },
    "slogan": "Aged in the elements.",
    "description": "No climate control, no roof leaks fixed. Whatever Kentucky did to it, you taste.",
    "brandValue": 55
  },
  {
    "id": "48",
    "name": "Bonded Beyond",
    "rarity": "Rare",
    "grid": [
      [
        9,
        11
      ]
    ],
    "awards": null,
    "ageBands": [
      2
    ],
    "demandBands": [
      0,
      6
    ],
    "tier": "common",
    "slogan": "Four years isn't enough.",
    "description": "Bottled-in-bond at twelve, when most are tired. The rare BiB that earns its prefix."
  },
  {
    "id": "49",
    "name": "Oak Oracle",
    "rarity": "Rare",
    "grid": [
      [
        5,
        9
      ]
    ],
    "awards": null,
    "ageBands": [
      2
    ],
    "demandBands": [
      0,
      6
    ],
    "tier": "common",
    "slogan": "Reads the cask, foretells the price.",
    "description": "Master cooper's pick — the staves were chosen for tone before they were assembled."
  },
  {
    "id": "50",
    "name": "The Last Rick",
    "rarity": "Rare",
    "grid": [
      [
        6,
        10
      ]
    ],
    "awards": null,
    "ageBands": [
      2
    ],
    "demandBands": [
      0,
      6
    ],
    "tier": "common",
    "slogan": "Shutdown distillery, final pull.",
    "description": "Last barrel to leave the warehouse before the auction. Bottled, sealed, sold."
  },
  {
    "id": "51",
    "name": "Moonlit Mash",
    "rarity": "Standard",
    "grid": [
      [
        9,
        11
      ]
    ],
    "awards": null,
    "ageBands": [
      2
    ],
    "demandBands": [
      0,
      6
    ],
    "tier": "common",
    "slogan": "Cooked under a watching moon.",
    "description": "Late-shift batch run between midnight and three. Tastes like discipline."
  },
  {
    "id": "52",
    "name": "Backroad Batch",
    "rarity": "Standard",
    "grid": [
      [
        5,
        10
      ],
      [
        10,
        18
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      6
    ],
    "demandBands": [
      0,
      7
    ],
    "tier": "uncommon",
    "slogan": "Off the bourbon trail.",
    "description": "Made by a distillery the maps forgot. Word of mouth carries it now."
  },
  {
    "id": "53",
    "name": "Distiller's Dozen",
    "rarity": "Standard",
    "grid": [
      [
        6,
        11
      ],
      [
        11,
        20
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      6
    ],
    "demandBands": [
      0,
      7
    ],
    "tier": "uncommon",
    "slogan": "Twelve barrels, hand-picked.",
    "description": "The master distiller's personal selection from one season's run. Assertive, balanced, a little vain."
  },
  {
    "id": "54",
    "name": "Owensboro Drift",
    "rarity": "Standard",
    "grid": [
      [
        10,
        13,
        18
      ],
      [
        13,
        18,
        25
      ],
      [
        18,
        26,
        34
      ]
    ],
    "awards": {
      "silver": "Sell at demand **≥5** **and** mash satisfies the bill recipe."
    },
    "ageBands": [
      2,
      5,
      8
    ],
    "demandBands": [
      0,
      5,
      8
    ],
    "recipe": {
      "rye": {
        "min": 2
      }
    },
    "tier": "rare",
    "slogan": "Floats down the Ohio.",
    "description": "Western-Kentucky workhorse with river-cooled water. Smoother than the locals admit."
  },
  {
    "id": "55",
    "name": "Frankfort Flare",
    "rarity": "Standard",
    "grid": [
      [
        6,
        10,
        15
      ],
      [
        10,
        15,
        21
      ],
      [
        15,
        23,
        31
      ]
    ],
    "awards": {
      "silver": "Sell at demand **≥5** **and** mash satisfies the bill recipe."
    },
    "recipe": {
      "rye": {
        "min": 2
      }
    },
    "ageBands": [
      2,
      5,
      8
    ],
    "demandBands": [
      0,
      5,
      8
    ],
    "tier": "rare",
    "slogan": "Capital pour, no apologies.",
    "description": "Distilled within sight of the dome. Politicians' choice; everyone else's secret."
  },
  {
    "id": "56",
    "name": "Stave Society 88",
    "rarity": "Standard",
    "grid": [
      [
        16,
        20,
        23
      ],
      [
        20,
        26,
        33
      ],
      [
        25,
        33,
        41
      ]
    ],
    "awards": {
      "silver": "Barrel **≥7 years** **and** sell at demand **≥6** **and** mash satisfies the recipe.",
      "gold": "Barrel **≥10 years** **and** demand **≥8** at sale **and** mash satisfies the recipe (grid **maximum** **$25**)."
    },
    "ageBands": [
      4,
      7,
      10
    ],
    "demandBands": [
      4,
      6,
      8
    ],
    "tier": "epic",
    "recipe": {
      "rye": {
        "min": 2
      },
      "wheat": {
        "min": 1
      }
    },
    "slogan": "Members only, ages eight.",
    "description": "Cooperage co-op release — the staves were milled by the membership. Quietly excellent.",
    "brandValue": 50
  },
  {
    "id": "57",
    "name": "Copper Cadence",
    "rarity": "Standard",
    "grid": [
      [
        9,
        11
      ]
    ],
    "awards": null,
    "ageBands": [
      2
    ],
    "demandBands": [
      0,
      6
    ],
    "tier": "common",
    "slogan": "Beat of the still.",
    "description": "A pot still rhythm in every sip — three notes on entry, two on the back."
  },
  {
    "id": "58",
    "name": "Greenriver Gold",
    "rarity": "Standard",
    "grid": [
      [
        5,
        9
      ]
    ],
    "awards": null,
    "ageBands": [
      2
    ],
    "demandBands": [
      0,
      6
    ],
    "tier": "common",
    "slogan": "Western water, eastern aging.",
    "description": "Greenriver-distilled, central-Kentucky aged. Best of two basins in one bottle."
  },
  {
    "id": "59",
    "name": "Heirloom 1792",
    "rarity": "Standard",
    "grid": [
      [
        6,
        10
      ]
    ],
    "awards": null,
    "ageBands": [
      2
    ],
    "demandBands": [
      0,
      6
    ],
    "tier": "common",
    "slogan": "The year, the recipe, the reverence.",
    "description": "Reconstructed from a 1792 distillery's recovered notes. Historical accuracy, modern char."
  },
  {
    "id": "60",
    "name": "The Proofsmith",
    "rarity": "Standard",
    "grid": [
      [
        9,
        11
      ]
    ],
    "awards": null,
    "ageBands": [
      2
    ],
    "demandBands": [
      0,
      6
    ],
    "tier": "common",
    "slogan": "Forged at one hundred.",
    "description": "Hundred proof, hundred questions answered. The bartender's reference bottle."
  },
  {
    "id": "61",
    "name": "Phoenix Cooperage",
    "rarity": "Rare",
    "grid": [
      [
        5,
        10
      ],
      [
        10,
        18
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      6
    ],
    "demandBands": [
      0,
      7
    ],
    "tier": "uncommon",
    "slogan": "Burned, rebuilt, better.",
    "description": "Cooperage that burned in '78 and reopened in '79. Every cask carries the memory."
  },
  {
    "id": "62",
    "name": "Whisper Barrel",
    "rarity": "Rare",
    "grid": [
      [
        6,
        11
      ],
      [
        11,
        20
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      6
    ],
    "demandBands": [
      0,
      7
    ],
    "tier": "uncommon",
    "slogan": "It speaks if you listen.",
    "description": "Single-barrel release, ultra-low proof. Subtle to the point of evasion. Worth the lean-in."
  },
  {
    "id": "63",
    "name": "Midnight Mash Bill",
    "rarity": "Rare",
    "grid": [
      [
        9,
        13
      ],
      [
        13,
        21
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      6
    ],
    "demandBands": [
      0,
      7
    ],
    "tier": "uncommon",
    "slogan": "Cooked in the dark hours.",
    "description": "Third-shift mash that nobody wanted to claim. Turned out to be the year's best."
  },
  {
    "id": "64",
    "name": "Triple Crown Reserve",
    "rarity": "Rare",
    "grid": [
      [
        6,
        10,
        15
      ],
      [
        10,
        15,
        21
      ],
      [
        15,
        23,
        31
      ]
    ],
    "awards": {
      "silver": "Sell at demand **≥5** **and** mash satisfies the bill recipe."
    },
    "ageBands": [
      2,
      5,
      8
    ],
    "demandBands": [
      0,
      5,
      8
    ],
    "tier": "rare",
    "recipe": {
      "rye": {
        "min": 2
      }
    },
    "slogan": "Three races, three wins, three glasses.",
    "description": "Stored under three rickhouses, blended for the fall classic. Win, place, show."
  },
  {
    "id": "65",
    "name": "Black River Belle",
    "rarity": "Rare",
    "grid": [
      [
        16,
        20,
        23
      ],
      [
        20,
        26,
        33
      ],
      [
        25,
        33,
        41
      ]
    ],
    "awards": {
      "silver": "Barrel **≥7 years** **and** sell at demand **≥6** **and** mash satisfies the recipe.",
      "gold": "Barrel **≥10 years** **and** demand **≥8** at sale **and** mash satisfies the recipe (grid **maximum** **$25**)."
    },
    "ageBands": [
      4,
      7,
      10
    ],
    "demandBands": [
      4,
      6,
      8
    ],
    "tier": "epic",
    "recipe": {
      "rye": {
        "min": 2
      },
      "wheat": {
        "min": 1
      }
    },
    "slogan": "Dark water, bright finish.",
    "description": "Distilled along the Black River, finished in former sherry casks. Belle of the dinner table.",
    "brandValue": 55
  }
] as const;

export const BOURBON_CARDS_BY_ID: Readonly<Record<string, BourbonCardDef>> = Object.freeze(
  Object.fromEntries(BOURBON_CARDS.map((c) => [c.id, c]))
);
