/**
 * AUTOGENERATED — DO NOT EDIT.
 * Regenerated by scripts/build-catalogs.ts from data/*.yaml.
 */

import type { BourbonCardDef } from "./types";

export const BOURBON_CARDS: readonly BourbonCardDef[] = [
  {
    "id": "01",
    "name": "Knob's End 90",
    "rarity": "Standard",
    "grid": [
      [
        2,
        2,
        2
      ],
      [
        2,
        2,
        2
      ],
      [
        3,
        3,
        3
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      3,
      4
    ],
    "demandBands": [
      0,
      4,
      8
    ],
    "tier": "common"
  },
  {
    "id": "02",
    "name": "Mammoth Cave Malt",
    "rarity": "Standard",
    "grid": [
      [
        3,
        3,
        3
      ],
      [
        3,
        3,
        3
      ],
      [
        4,
        4,
        4
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      3,
      4
    ],
    "demandBands": [
      0,
      4,
      8
    ],
    "tier": "common"
  },
  {
    "id": "03",
    "name": "Bardstown Boiler",
    "rarity": "Standard",
    "grid": [
      [
        4,
        4,
        4
      ],
      [
        4,
        4,
        4
      ],
      [
        5,
        5,
        5
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      3,
      4
    ],
    "demandBands": [
      0,
      4,
      8
    ],
    "tier": "common"
  },
  {
    "id": "04",
    "name": "Limestone Ledger",
    "rarity": "Standard",
    "grid": [
      [
        2,
        2,
        2
      ],
      [
        2,
        2,
        2
      ],
      [
        3,
        3,
        3
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      3,
      4
    ],
    "demandBands": [
      0,
      4,
      8
    ],
    "tier": "common"
  },
  {
    "id": "05",
    "name": "Charred Oak Exchange",
    "rarity": "Standard",
    "grid": [
      [
        2,
        4,
        6
      ],
      [
        3,
        5,
        7
      ],
      [
        3,
        5,
        7
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      4,
      6
    ],
    "demandBands": [
      0,
      4,
      7
    ],
    "tier": "uncommon"
  },
  {
    "id": "06",
    "name": "Riverbend Rye Signal",
    "rarity": "Standard",
    "grid": [
      [
        3,
        5,
        7
      ],
      [
        4,
        6,
        8
      ],
      [
        4,
        6,
        8
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      4,
      6
    ],
    "demandBands": [
      0,
      4,
      7
    ],
    "tier": "uncommon"
  },
  {
    "id": "07",
    "name": "Stave & Story",
    "rarity": "Standard",
    "grid": [
      [
        2,
        4,
        6
      ],
      [
        3,
        5,
        7
      ],
      [
        3,
        5,
        7
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      4,
      6
    ],
    "demandBands": [
      0,
      4,
      7
    ],
    "tier": "uncommon"
  },
  {
    "id": "08",
    "name": "Cooper's Quorum",
    "rarity": "Standard",
    "grid": [
      [
        4,
        5,
        7
      ],
      [
        6,
        9,
        12
      ],
      [
        8,
        13,
        16
      ]
    ],
    "awards": {
      "silver": "Sell at demand **≥6** **and** mash satisfies the bill recipe."
    },
    "ageBands": [
      2,
      5,
      8
    ],
    "demandBands": [
      3,
      6,
      9
    ],
    "tier": "rare",
    "recipe": {
      "barley": {
        "min": 1
      },
      "rye": {
        "min": 1
      },
      "wheat": {
        "min": 1
      }
    }
  },
  {
    "id": "09",
    "name": "Mash Bill No. 7",
    "rarity": "Standard",
    "grid": [
      [
        0,
        0,
        9
      ],
      [
        0,
        14,
        21
      ],
      [
        9,
        21,
        30
      ]
    ],
    "awards": {
      "silver": "Barrel **≥7 years** **and** sell at demand **≥7** **and** mash satisfies the recipe.",
      "gold": "Barrel **≥10 years** **and** demand **≥10** at sale **and** mash satisfies the recipe (grid **maximum** **$30**)."
    },
    "ageBands": [
      4,
      7,
      10
    ],
    "demandBands": [
      4,
      7,
      10
    ],
    "tier": "epic",
    "recipe": {
      "rye": {
        "min": 2
      },
      "wheat": {
        "min": 1
      }
    },
    "brandValue": 35
  },
  {
    "id": "10",
    "name": "High Rickhouse Select",
    "rarity": "Standard",
    "grid": [
      [
        0,
        20,
        30
      ],
      [
        0,
        28,
        35
      ],
      [
        15,
        35,
        50
      ]
    ],
    "awards": {
      "silver": "Barrel **≥10 years** **and** demand **≥8** at sale **and** mash satisfies the recipe.",
      "gold": "Barrel **≥15 years** **and** demand **≥10** at sale **and** mash uses **≥4 grain cards** with a specialty cask (grid **maximum** **$50**)."
    },
    "ageBands": [
      8,
      10,
      15
    ],
    "demandBands": [
      4,
      8,
      10
    ],
    "tier": "legendary",
    "recipe": {
      "grain": {
        "min": 4
      },
      "rye": {
        "min": 1
      },
      "wheat": {
        "min": 1
      }
    },
    "brandValue": 55
  },
  {
    "id": "11",
    "name": "Warehouse E Batch",
    "rarity": "Standard",
    "grid": [
      [
        3,
        3,
        3
      ],
      [
        3,
        3,
        3
      ],
      [
        4,
        4,
        4
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      3,
      4
    ],
    "demandBands": [
      0,
      4,
      8
    ],
    "tier": "common"
  },
  {
    "id": "12",
    "name": "Foggy Bottom Forge",
    "rarity": "Standard",
    "grid": [
      [
        4,
        4,
        4
      ],
      [
        4,
        4,
        4
      ],
      [
        5,
        5,
        5
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      3,
      4
    ],
    "demandBands": [
      0,
      4,
      8
    ],
    "tier": "common"
  },
  {
    "id": "13",
    "name": "Cornbread Line",
    "rarity": "Standard",
    "grid": [
      [
        2,
        2,
        2
      ],
      [
        2,
        2,
        2
      ],
      [
        3,
        3,
        3
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      3,
      4
    ],
    "demandBands": [
      0,
      4,
      8
    ],
    "tier": "common"
  },
  {
    "id": "14",
    "name": "Rye Ladder 95",
    "rarity": "Standard",
    "grid": [
      [
        3,
        5,
        7
      ],
      [
        4,
        6,
        8
      ],
      [
        4,
        6,
        8
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      4,
      6
    ],
    "demandBands": [
      0,
      4,
      7
    ],
    "tier": "uncommon"
  },
  {
    "id": "15",
    "name": "Wheat Whisper",
    "rarity": "Standard",
    "grid": [
      [
        2,
        4,
        6
      ],
      [
        3,
        5,
        7
      ],
      [
        3,
        5,
        7
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      4,
      6
    ],
    "demandBands": [
      0,
      4,
      7
    ],
    "tier": "uncommon"
  },
  {
    "id": "16",
    "name": "Barley Bastion",
    "rarity": "Standard",
    "grid": [
      [
        3,
        5,
        7
      ],
      [
        4,
        6,
        8
      ],
      [
        4,
        6,
        8
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      4,
      6
    ],
    "demandBands": [
      0,
      4,
      7
    ],
    "tier": "uncommon"
  },
  {
    "id": "17",
    "name": "Two Charring Points",
    "rarity": "Standard",
    "grid": [
      [
        4,
        5,
        7
      ],
      [
        6,
        9,
        12
      ],
      [
        8,
        13,
        16
      ]
    ],
    "awards": {
      "silver": "Sell at demand **≥6** **and** mash satisfies the bill recipe."
    },
    "ageBands": [
      2,
      5,
      8
    ],
    "demandBands": [
      3,
      6,
      9
    ],
    "tier": "rare",
    "recipe": {
      "rye": {
        "min": 2
      }
    }
  },
  {
    "id": "18",
    "name": "Angel's Trace",
    "rarity": "Standard",
    "grid": [
      [
        5,
        6,
        8
      ],
      [
        7,
        10,
        13
      ],
      [
        9,
        14,
        17
      ]
    ],
    "awards": {
      "silver": "Sell at demand **≥6** **and** mash satisfies the bill recipe."
    },
    "ageBands": [
      2,
      5,
      8
    ],
    "demandBands": [
      3,
      6,
      9
    ],
    "tier": "rare",
    "recipe": {
      "rye": {
        "min": 2
      }
    }
  },
  {
    "id": "19",
    "name": "Bonded & Bold",
    "rarity": "Standard",
    "grid": [
      [
        0,
        0,
        7
      ],
      [
        0,
        11,
        17
      ],
      [
        7,
        17,
        24
      ]
    ],
    "awards": {
      "silver": "Barrel **≥7 years** **and** sell at demand **≥7** **and** mash satisfies the recipe.",
      "gold": "Barrel **≥10 years** **and** demand **≥10** at sale **and** mash satisfies the recipe (grid **maximum** **$24**)."
    },
    "ageBands": [
      4,
      7,
      10
    ],
    "demandBands": [
      4,
      7,
      10
    ],
    "tier": "epic",
    "recipe": {
      "rye": {
        "min": 2
      },
      "wheat": {
        "min": 1
      }
    },
    "brandValue": 30
  },
  {
    "id": "20",
    "name": "Cork & Crown",
    "rarity": "Standard",
    "grid": [
      [
        3,
        3,
        3
      ],
      [
        3,
        3,
        3
      ],
      [
        4,
        4,
        4
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      3,
      4
    ],
    "demandBands": [
      0,
      4,
      8
    ],
    "tier": "common"
  },
  {
    "id": "21",
    "name": "Proof Positive 100",
    "rarity": "Standard",
    "grid": [
      [
        4,
        4,
        4
      ],
      [
        4,
        4,
        4
      ],
      [
        5,
        5,
        5
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      3,
      4
    ],
    "demandBands": [
      0,
      4,
      8
    ],
    "tier": "common"
  },
  {
    "id": "22",
    "name": "Sour Mash Society",
    "rarity": "Standard",
    "grid": [
      [
        2,
        2,
        2
      ],
      [
        2,
        2,
        2
      ],
      [
        3,
        3,
        3
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      3,
      4
    ],
    "demandBands": [
      0,
      4,
      8
    ],
    "tier": "common"
  },
  {
    "id": "23",
    "name": "Stillhouse Sonnet",
    "rarity": "Standard",
    "grid": [
      [
        3,
        3,
        3
      ],
      [
        3,
        3,
        3
      ],
      [
        4,
        4,
        4
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      3,
      4
    ],
    "demandBands": [
      0,
      4,
      8
    ],
    "tier": "common"
  },
  {
    "id": "24",
    "name": "Patent Still 04",
    "rarity": "Standard",
    "grid": [
      [
        3,
        5,
        7
      ],
      [
        4,
        6,
        8
      ],
      [
        4,
        6,
        8
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      4,
      6
    ],
    "demandBands": [
      0,
      4,
      7
    ],
    "tier": "uncommon"
  },
  {
    "id": "25",
    "name": "Kentucky Crosscut",
    "rarity": "Standard",
    "grid": [
      [
        2,
        4,
        6
      ],
      [
        3,
        5,
        7
      ],
      [
        3,
        5,
        7
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      4,
      6
    ],
    "demandBands": [
      0,
      4,
      7
    ],
    "tier": "uncommon"
  },
  {
    "id": "26",
    "name": "Oak Algebra",
    "rarity": "Standard",
    "grid": [
      [
        3,
        5,
        7
      ],
      [
        4,
        6,
        8
      ],
      [
        4,
        6,
        8
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      4,
      6
    ],
    "demandBands": [
      0,
      4,
      7
    ],
    "tier": "uncommon"
  },
  {
    "id": "27",
    "name": "Bottled Lightning 86",
    "rarity": "Standard",
    "grid": [
      [
        5,
        6,
        8
      ],
      [
        7,
        10,
        13
      ],
      [
        9,
        14,
        17
      ]
    ],
    "awards": {
      "silver": "Sell at demand **≥6** **and** mash satisfies the bill recipe."
    },
    "ageBands": [
      2,
      5,
      8
    ],
    "demandBands": [
      3,
      6,
      9
    ],
    "recipe": {
      "rye": {
        "min": 2
      }
    },
    "tier": "rare"
  },
  {
    "id": "28",
    "name": "Copper Trace",
    "rarity": "Standard",
    "grid": [
      [
        0,
        0,
        7
      ],
      [
        0,
        11,
        17
      ],
      [
        7,
        17,
        24
      ]
    ],
    "awards": {
      "silver": "Barrel **≥7 years** **and** sell at demand **≥7** **and** mash satisfies the recipe.",
      "gold": "Barrel **≥10 years** **and** demand **≥10** at sale **and** mash satisfies the recipe (grid **maximum** **$24**)."
    },
    "ageBands": [
      4,
      7,
      10
    ],
    "demandBands": [
      4,
      7,
      10
    ],
    "recipe": {
      "rye": {
        "min": 2
      },
      "wheat": {
        "min": 1
      }
    },
    "tier": "epic",
    "brandValue": 30
  },
  {
    "id": "29",
    "name": "Bluegrass Boiler",
    "rarity": "Standard",
    "grid": [
      [
        3,
        3,
        3
      ],
      [
        3,
        3,
        3
      ],
      [
        4,
        4,
        4
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      3,
      4
    ],
    "demandBands": [
      0,
      4,
      8
    ],
    "tier": "common"
  },
  {
    "id": "30",
    "name": "Rickhouse Arithmetic",
    "rarity": "Standard",
    "grid": [
      [
        4,
        4,
        4
      ],
      [
        4,
        4,
        4
      ],
      [
        5,
        5,
        5
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      3,
      4
    ],
    "demandBands": [
      0,
      4,
      8
    ],
    "tier": "common"
  },
  {
    "id": "31",
    "name": "Filtered Lore",
    "rarity": "Standard",
    "grid": [
      [
        2,
        2,
        2
      ],
      [
        2,
        2,
        2
      ],
      [
        3,
        3,
        3
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      3,
      4
    ],
    "demandBands": [
      0,
      4,
      8
    ],
    "tier": "common"
  },
  {
    "id": "32",
    "name": "Low Gauge Legacy",
    "rarity": "Standard",
    "grid": [
      [
        3,
        3,
        3
      ],
      [
        3,
        3,
        3
      ],
      [
        4,
        4,
        4
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      3,
      4
    ],
    "demandBands": [
      0,
      4,
      8
    ],
    "tier": "common"
  },
  {
    "id": "33",
    "name": "Steam Furnace Five",
    "rarity": "Standard",
    "grid": [
      [
        2,
        4,
        6
      ],
      [
        3,
        5,
        7
      ],
      [
        3,
        5,
        7
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      4,
      6
    ],
    "demandBands": [
      0,
      4,
      7
    ],
    "tier": "uncommon"
  },
  {
    "id": "34",
    "name": "Grist Galaxy",
    "rarity": "Standard",
    "grid": [
      [
        3,
        5,
        7
      ],
      [
        4,
        6,
        8
      ],
      [
        4,
        6,
        8
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      4,
      6
    ],
    "demandBands": [
      0,
      4,
      7
    ],
    "tier": "uncommon"
  },
  {
    "id": "35",
    "name": "Turf & Tarnish",
    "rarity": "Standard",
    "grid": [
      [
        2,
        4,
        6
      ],
      [
        3,
        5,
        7
      ],
      [
        3,
        5,
        7
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      4,
      6
    ],
    "demandBands": [
      0,
      4,
      7
    ],
    "tier": "uncommon"
  },
  {
    "id": "36",
    "name": "Copper Crossings 107",
    "rarity": "Rare",
    "grid": [
      [
        5,
        6,
        8
      ],
      [
        7,
        10,
        13
      ],
      [
        9,
        14,
        17
      ]
    ],
    "awards": {
      "silver": "Sell at demand **≥6** **and** mash satisfies the bill recipe."
    },
    "ageBands": [
      2,
      5,
      8
    ],
    "demandBands": [
      3,
      6,
      9
    ],
    "recipe": {
      "rye": {
        "min": 2
      }
    },
    "tier": "rare"
  },
  {
    "id": "37",
    "name": "Seven Stars Odd Lot",
    "rarity": "Rare",
    "grid": [
      [
        0,
        0,
        7
      ],
      [
        0,
        11,
        17
      ],
      [
        7,
        17,
        24
      ]
    ],
    "awards": {
      "silver": "Barrel **≥7 years** **and** sell at demand **≥7** **and** mash satisfies the recipe.",
      "gold": "Barrel **≥10 years** **and** demand **≥10** at sale **and** mash satisfies the recipe (grid **maximum** **$24**)."
    },
    "ageBands": [
      4,
      7,
      10
    ],
    "demandBands": [
      4,
      7,
      10
    ],
    "tier": "epic",
    "recipe": {
      "rye": {
        "min": 2
      },
      "wheat": {
        "min": 1
      }
    },
    "brandValue": 35
  },
  {
    "id": "38",
    "name": "State Line BiB",
    "rarity": "Rare",
    "grid": [
      [
        0,
        23,
        35
      ],
      [
        0,
        32,
        41
      ],
      [
        17,
        41,
        58
      ]
    ],
    "awards": {
      "silver": "Barrel **≥10 years** **and** demand **≥8** at sale **and** mash satisfies the recipe.",
      "gold": "Barrel **≥15 years** **and** demand **≥10** at sale **and** mash uses **≥4 grain cards** with a specialty cask (grid **maximum** **$58**)."
    },
    "ageBands": [
      8,
      10,
      15
    ],
    "demandBands": [
      4,
      8,
      10
    ],
    "tier": "legendary",
    "recipe": {
      "grain": {
        "min": 4
      },
      "rye": {
        "min": 1
      },
      "wheat": {
        "min": 1
      }
    },
    "brandValue": 70
  },
  {
    "id": "39",
    "name": "Barrel Thief Reserve",
    "rarity": "Rare",
    "grid": [
      [
        4,
        4,
        4
      ],
      [
        4,
        4,
        4
      ],
      [
        5,
        5,
        5
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      3,
      4
    ],
    "demandBands": [
      0,
      4,
      8
    ],
    "tier": "common"
  },
  {
    "id": "40",
    "name": "Ghost Warehouse",
    "rarity": "Rare",
    "grid": [
      [
        2,
        2,
        2
      ],
      [
        2,
        2,
        2
      ],
      [
        3,
        3,
        3
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      3,
      4
    ],
    "demandBands": [
      0,
      4,
      8
    ],
    "tier": "common"
  },
  {
    "id": "41",
    "name": "Double Stack Destiny",
    "rarity": "Rare",
    "grid": [
      [
        3,
        3,
        3
      ],
      [
        3,
        3,
        3
      ],
      [
        4,
        4,
        4
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      3,
      4
    ],
    "demandBands": [
      0,
      4,
      8
    ],
    "tier": "common"
  },
  {
    "id": "42",
    "name": "Crimson Corn Covenant",
    "rarity": "Rare",
    "grid": [
      [
        3,
        5,
        7
      ],
      [
        4,
        6,
        8
      ],
      [
        4,
        6,
        8
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      4,
      6
    ],
    "demandBands": [
      0,
      4,
      7
    ],
    "tier": "uncommon"
  },
  {
    "id": "43",
    "name": "Platinum Rick Proof",
    "rarity": "Rare",
    "grid": [
      [
        2,
        4,
        6
      ],
      [
        3,
        5,
        7
      ],
      [
        3,
        5,
        7
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      4,
      6
    ],
    "demandBands": [
      0,
      4,
      7
    ],
    "tier": "uncommon"
  },
  {
    "id": "44",
    "name": "Infinite Stave",
    "rarity": "Rare",
    "grid": [
      [
        3,
        5,
        7
      ],
      [
        4,
        6,
        8
      ],
      [
        4,
        6,
        8
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      4,
      6
    ],
    "demandBands": [
      0,
      4,
      7
    ],
    "tier": "uncommon"
  },
  {
    "id": "45",
    "name": "Crown Compass",
    "rarity": "Rare",
    "grid": [
      [
        5,
        6,
        8
      ],
      [
        7,
        10,
        13
      ],
      [
        9,
        14,
        17
      ]
    ],
    "awards": {
      "silver": "Sell at demand **≥6** **and** mash satisfies the bill recipe."
    },
    "ageBands": [
      2,
      5,
      8
    ],
    "demandBands": [
      3,
      6,
      9
    ],
    "recipe": {
      "rye": {
        "min": 2
      }
    },
    "tier": "rare"
  },
  {
    "id": "46",
    "name": "Ledger Luxe",
    "rarity": "Rare",
    "grid": [
      [
        3,
        4,
        6
      ],
      [
        5,
        8,
        11
      ],
      [
        7,
        12,
        15
      ]
    ],
    "awards": {
      "silver": "Sell at demand **≥6** **and** mash satisfies the bill recipe."
    },
    "ageBands": [
      2,
      5,
      8
    ],
    "demandBands": [
      3,
      6,
      9
    ],
    "recipe": {
      "rye": {
        "min": 2
      }
    },
    "tier": "rare"
  },
  {
    "id": "47",
    "name": "Wild Rickhouse",
    "rarity": "Rare",
    "grid": [
      [
        0,
        0,
        8
      ],
      [
        0,
        12,
        19
      ],
      [
        8,
        19,
        27
      ]
    ],
    "awards": {
      "silver": "Barrel **≥7 years** **and** sell at demand **≥7** **and** mash satisfies the recipe.",
      "gold": "Barrel **≥10 years** **and** demand **≥10** at sale **and** mash satisfies the recipe (grid **maximum** **$27**)."
    },
    "ageBands": [
      4,
      7,
      10
    ],
    "demandBands": [
      4,
      7,
      10
    ],
    "tier": "epic",
    "recipe": {
      "rye": {
        "min": 2
      },
      "wheat": {
        "min": 1
      }
    },
    "brandValue": 40
  },
  {
    "id": "48",
    "name": "Bonded Beyond",
    "rarity": "Rare",
    "grid": [
      [
        4,
        4,
        4
      ],
      [
        4,
        4,
        4
      ],
      [
        5,
        5,
        5
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      3,
      4
    ],
    "demandBands": [
      0,
      4,
      8
    ],
    "tier": "common"
  },
  {
    "id": "49",
    "name": "Oak Oracle",
    "rarity": "Rare",
    "grid": [
      [
        2,
        2,
        2
      ],
      [
        2,
        2,
        2
      ],
      [
        3,
        3,
        3
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      3,
      4
    ],
    "demandBands": [
      0,
      4,
      8
    ],
    "tier": "common"
  },
  {
    "id": "50",
    "name": "The Last Rick",
    "rarity": "Rare",
    "grid": [
      [
        3,
        3,
        3
      ],
      [
        3,
        3,
        3
      ],
      [
        4,
        4,
        4
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      3,
      4
    ],
    "demandBands": [
      0,
      4,
      8
    ],
    "tier": "common"
  },
  {
    "id": "51",
    "name": "Moonlit Mash",
    "rarity": "Standard",
    "grid": [
      [
        4,
        4,
        4
      ],
      [
        4,
        4,
        4
      ],
      [
        5,
        5,
        5
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      3,
      4
    ],
    "demandBands": [
      0,
      4,
      8
    ],
    "tier": "common"
  },
  {
    "id": "52",
    "name": "Backroad Batch",
    "rarity": "Standard",
    "grid": [
      [
        3,
        5,
        7
      ],
      [
        4,
        6,
        8
      ],
      [
        4,
        6,
        8
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      4,
      6
    ],
    "demandBands": [
      0,
      4,
      7
    ],
    "tier": "uncommon"
  },
  {
    "id": "53",
    "name": "Distiller's Dozen",
    "rarity": "Standard",
    "grid": [
      [
        2,
        4,
        6
      ],
      [
        3,
        5,
        7
      ],
      [
        3,
        5,
        7
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      4,
      6
    ],
    "demandBands": [
      0,
      4,
      7
    ],
    "tier": "uncommon"
  },
  {
    "id": "54",
    "name": "Owensboro Drift",
    "rarity": "Standard",
    "grid": [
      [
        5,
        6,
        8
      ],
      [
        7,
        10,
        13
      ],
      [
        9,
        14,
        17
      ]
    ],
    "awards": {
      "silver": "Sell at demand **≥6** **and** mash satisfies the bill recipe."
    },
    "ageBands": [
      2,
      5,
      8
    ],
    "demandBands": [
      3,
      6,
      9
    ],
    "recipe": {
      "rye": {
        "min": 2
      }
    },
    "tier": "rare"
  },
  {
    "id": "55",
    "name": "Frankfort Flare",
    "rarity": "Standard",
    "grid": [
      [
        3,
        4,
        6
      ],
      [
        5,
        8,
        11
      ],
      [
        7,
        12,
        15
      ]
    ],
    "awards": {
      "silver": "Sell at demand **≥6** **and** mash satisfies the bill recipe."
    },
    "recipe": {
      "rye": {
        "min": 2
      }
    },
    "ageBands": [
      2,
      5,
      8
    ],
    "demandBands": [
      3,
      6,
      9
    ],
    "tier": "rare"
  },
  {
    "id": "56",
    "name": "Stave Society 88",
    "rarity": "Standard",
    "grid": [
      [
        0,
        0,
        8
      ],
      [
        0,
        12,
        19
      ],
      [
        8,
        19,
        27
      ]
    ],
    "awards": {
      "silver": "Barrel **≥7 years** **and** sell at demand **≥7** **and** mash satisfies the recipe.",
      "gold": "Barrel **≥10 years** **and** demand **≥10** at sale **and** mash satisfies the recipe (grid **maximum** **$27**)."
    },
    "ageBands": [
      4,
      7,
      10
    ],
    "demandBands": [
      4,
      7,
      10
    ],
    "tier": "epic",
    "recipe": {
      "rye": {
        "min": 2
      },
      "wheat": {
        "min": 1
      }
    },
    "brandValue": 35
  },
  {
    "id": "57",
    "name": "Copper Cadence",
    "rarity": "Standard",
    "grid": [
      [
        4,
        4,
        4
      ],
      [
        4,
        4,
        4
      ],
      [
        5,
        5,
        5
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      3,
      4
    ],
    "demandBands": [
      0,
      4,
      8
    ],
    "tier": "common"
  },
  {
    "id": "58",
    "name": "Greenriver Gold",
    "rarity": "Standard",
    "grid": [
      [
        2,
        2,
        2
      ],
      [
        2,
        2,
        2
      ],
      [
        3,
        3,
        3
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      3,
      4
    ],
    "demandBands": [
      0,
      4,
      8
    ],
    "tier": "common"
  },
  {
    "id": "59",
    "name": "Heirloom 1792",
    "rarity": "Standard",
    "grid": [
      [
        3,
        3,
        3
      ],
      [
        3,
        3,
        3
      ],
      [
        4,
        4,
        4
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      3,
      4
    ],
    "demandBands": [
      0,
      4,
      8
    ],
    "tier": "common"
  },
  {
    "id": "60",
    "name": "The Proofsmith",
    "rarity": "Standard",
    "grid": [
      [
        4,
        4,
        4
      ],
      [
        4,
        4,
        4
      ],
      [
        5,
        5,
        5
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      3,
      4
    ],
    "demandBands": [
      0,
      4,
      8
    ],
    "tier": "common"
  },
  {
    "id": "61",
    "name": "Phoenix Cooperage",
    "rarity": "Rare",
    "grid": [
      [
        2,
        4,
        6
      ],
      [
        3,
        5,
        7
      ],
      [
        3,
        5,
        7
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      4,
      6
    ],
    "demandBands": [
      0,
      4,
      7
    ],
    "tier": "uncommon"
  },
  {
    "id": "62",
    "name": "Whisper Barrel",
    "rarity": "Rare",
    "grid": [
      [
        3,
        5,
        7
      ],
      [
        4,
        6,
        8
      ],
      [
        4,
        6,
        8
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      4,
      6
    ],
    "demandBands": [
      0,
      4,
      7
    ],
    "tier": "uncommon"
  },
  {
    "id": "63",
    "name": "Midnight Mash Bill",
    "rarity": "Rare",
    "grid": [
      [
        2,
        4,
        6
      ],
      [
        3,
        5,
        7
      ],
      [
        3,
        5,
        7
      ]
    ],
    "awards": null,
    "ageBands": [
      2,
      4,
      6
    ],
    "demandBands": [
      0,
      4,
      7
    ],
    "tier": "uncommon"
  },
  {
    "id": "64",
    "name": "Triple Crown Reserve",
    "rarity": "Rare",
    "grid": [
      [
        3,
        4,
        6
      ],
      [
        5,
        8,
        11
      ],
      [
        7,
        12,
        15
      ]
    ],
    "awards": {
      "silver": "Sell at demand **≥6** **and** mash satisfies the bill recipe."
    },
    "ageBands": [
      2,
      5,
      8
    ],
    "demandBands": [
      3,
      6,
      9
    ],
    "tier": "rare",
    "recipe": {
      "rye": {
        "min": 2
      }
    }
  },
  {
    "id": "65",
    "name": "Black River Belle",
    "rarity": "Rare",
    "grid": [
      [
        0,
        0,
        8
      ],
      [
        0,
        12,
        19
      ],
      [
        8,
        19,
        27
      ]
    ],
    "awards": {
      "silver": "Barrel **≥7 years** **and** sell at demand **≥7** **and** mash satisfies the recipe.",
      "gold": "Barrel **≥10 years** **and** demand **≥10** at sale **and** mash satisfies the recipe (grid **maximum** **$27**)."
    },
    "ageBands": [
      4,
      7,
      10
    ],
    "demandBands": [
      4,
      7,
      10
    ],
    "tier": "epic",
    "recipe": {
      "rye": {
        "min": 2
      },
      "wheat": {
        "min": 1
      }
    },
    "brandValue": 40
  }
] as const;

export const BOURBON_CARDS_BY_ID: Readonly<Record<string, BourbonCardDef>> = Object.freeze(
  Object.fromEntries(BOURBON_CARDS.map((c) => [c.id, c]))
);
