/**
 * AUTOGENERATED — DO NOT EDIT.
 * Regenerated by scripts/build-catalogs.ts from data/*.yaml.
 */

import type { DistilleryCardDef } from "./types";

export const DISTILLERY_CARDS: readonly DistilleryCardDef[] = [
  {
    "id": "hot_mash",
    "name": "The Hot Mash",
    "flavor": "First barrel down, last one finished — speed wins quarters.",
    "bonus_text": "Begin with 1 Cask, 1 Corn, and 1 Rye in hand — a complete legal mash, ready to barrel on your first action.",
    "perk_text": "Once per round, your first MAKE_BOURBON action costs $0 regardless of the lap-cost ladder.",
    "bonuses": [
      {
        "kind": "resources",
        "cards": [
          {
            "resource": "cask",
            "count": 1
          },
          {
            "resource": "corn",
            "count": 1
          },
          {
            "resource": "rye",
            "count": 1
          }
        ]
      }
    ],
    "perk": {
      "kind": "free_make_per_round"
    }
  },
  {
    "id": "heritage_house",
    "name": "The Heritage House",
    "flavor": "Time is the only ingredient nobody can hurry.",
    "bonus_text": "Begin with $10 extra cash ($50 total).",
    "perk_text": "Each barrel you place enters the rickhouse at age 1 instead of age 0.",
    "bonuses": [
      {
        "kind": "cash",
        "amount": 10
      }
    ],
    "perk": {
      "kind": "barrel_age_bonus",
      "extra": 1
    }
  },
  {
    "id": "diaspora",
    "name": "The Diaspora",
    "flavor": "Six warehouses, six microclimates. Let everyone else fight over one.",
    "bonus_text": "Begin with $5 extra cash and 1 extra mash bill (5 total).",
    "perk_text": "You pay $0 rent on barrels in any rickhouse where you are the only baron present.",
    "bonuses": [
      {
        "kind": "cash",
        "amount": 5
      },
      {
        "kind": "mash_bills",
        "count": 1
      }
    ],
    "perk": {
      "kind": "solo_rickhouse_no_rent"
    }
  },
  {
    "id": "speculator",
    "name": "The Speculator",
    "flavor": "Demand is rumor with a publication date.",
    "bonus_text": "At setup, peek at the top 3 Market cards (no rearrange in this build).",
    "perk_text": "Your first sale each round does not reduce the global demand counter.",
    "bonuses": [
      {
        "kind": "peek_market",
        "count": 3
      }
    ],
    "perk": {
      "kind": "first_sale_no_demand_drop"
    }
  },
  {
    "id": "recipe_book",
    "name": "The Recipe Book",
    "flavor": "Every great whiskey starts with a number on a notepad.",
    "bonus_text": "Begin with 2 extra mash bills (6 total).",
    "perk_text": "Whenever you draw a mash bill, draw 2 and keep 1 (the other returns to the bottom of the deck).",
    "bonuses": [
      {
        "kind": "mash_bills",
        "count": 2
      }
    ],
    "perk": {
      "kind": "draw_two_keep_one_bourbon"
    }
  },
  {
    "id": "distillers_guild",
    "name": "The Distillers' Guild",
    "flavor": "We have a process for that. Several, actually.",
    "bonus_text": "Begin with 2 Operations cards already in hand.",
    "perk_text": "When you resolve an Operations card, immediately draw 1 replacement Operations card.",
    "bonuses": [
      {
        "kind": "operations",
        "count": 2
      }
    ],
    "perk": {
      "kind": "draw_replacement_on_ops"
    }
  },
  {
    "id": "bootlegger",
    "name": "The Bootlegger",
    "flavor": "Money makes barrels. Barrels make more money. Repeat.",
    "bonus_text": "Begin with $10 extra cash ($50 total).",
    "perk_text": "Your paid actions cost $1 less than the current lap tier (with a $0 floor).",
    "bonuses": [
      {
        "kind": "cash",
        "amount": 10
      }
    ],
    "perk": {
      "kind": "paid_action_discount",
      "amount": 1
    }
  },
  {
    "id": "cooperage",
    "name": "The Cooperage",
    "flavor": "Wood is wisdom. We know what wood remembers.",
    "bonus_text": "Begin with 3 Cask cards in hand.",
    "perk_text": "Once per round, when you make a bourbon, one Cask card from the mash returns to your hand instead of being spent.",
    "bonuses": [
      {
        "kind": "resources",
        "cards": [
          {
            "resource": "cask",
            "count": 3
          }
        ]
      }
    ],
    "perk": {
      "kind": "free_cask_reuse_per_round"
    }
  }
] as const;

export const DISTILLERY_CARDS_BY_ID: Readonly<Record<string, DistilleryCardDef>> = Object.freeze(
  Object.fromEntries(DISTILLERY_CARDS.map((c) => [c.id, c]))
);
