/**
 * AUTOGENERATED — DO NOT EDIT.
 * Regenerated by scripts/build-catalogs.ts from data/*.yaml.
 */

/**
 * AUTOGENERATED — DO NOT EDIT.
 * Source: data/market_cards.yaml. Run `npm run build:catalogs` to regenerate.
 */

import type { MarketCardDef } from "./types";

export const MARKET_CARDS: readonly MarketCardDef[] = [
  {
    "id": "holiday_rush",
    "title": "Holiday rush",
    "effect": "Demand **+2** next round.",
    "deckCopies": 3,
    "resolved": {
      "kind": "demand_delta",
      "delta": 2
    }
  },
  {
    "id": "export_deal",
    "title": "Export deal",
    "effect": "A foreign distributor signs on. Demand **+2** next round.",
    "deckCopies": 3,
    "resolved": {
      "kind": "demand_delta",
      "delta": 2
    }
  },
  {
    "id": "cocktail_renaissance",
    "title": "Cocktail renaissance",
    "effect": "Old fashioneds are back. Demand **+1**, persistent for **2 rounds**.",
    "deckCopies": 2,
    "resolved": {
      "kind": "persistent_demand_delta",
      "delta": 1,
      "extraRounds": 1
    }
  },
  {
    "id": "festival_week",
    "title": "Festival week",
    "effect": "The annual festival drives buyers in. Demand **+1** next round.",
    "deckCopies": 2,
    "resolved": {
      "kind": "demand_delta",
      "delta": 1
    }
  },
  {
    "id": "bourbon_convention",
    "title": "Bourbon convention",
    "effect": "Industry meet-up. **All players** draw **1** mash bill from the Bourbon deck now.",
    "deckCopies": 2,
    "resolved": {
      "kind": "all_draw_bourbon",
      "count": 1
    }
  },
  {
    "id": "economic_downturn",
    "title": "Economic downturn",
    "effect": "Tightened wallets. Demand **−2** next round.",
    "deckCopies": 2,
    "resolved": {
      "kind": "demand_delta",
      "delta": -2
    }
  },
  {
    "id": "health_trend",
    "title": "Health trend",
    "effect": "A wellness wave pulls drinkers away. Demand **−1**, persistent for **2 rounds**.",
    "deckCopies": 2,
    "resolved": {
      "kind": "persistent_demand_delta",
      "delta": -1,
      "extraRounds": 1
    }
  },
  {
    "id": "tariff_shock",
    "title": "Tariff shock",
    "effect": "Import duties bite. Demand **−2** next round.",
    "deckCopies": 2,
    "resolved": {
      "kind": "demand_delta",
      "delta": -2
    }
  },
  {
    "id": "tax_hike",
    "title": "Tax hike",
    "effect": "Every barrel pays **+$1** rent next round.",
    "deckCopies": 2,
    "resolved": {
      "kind": "rent_surcharge",
      "surcharge": 1
    }
  },
  {
    "id": "cooperage_strike",
    "title": "Cooperage strike",
    "effect": "Coopers strike — **cask** pile is locked next round.",
    "deckCopies": 2,
    "resolved": {
      "kind": "resource_shortage",
      "resource": "cask"
    }
  },
  {
    "id": "corn_blight",
    "title": "Corn blight",
    "effect": "A bad season locks the **corn** pile next round.",
    "deckCopies": 2,
    "resolved": {
      "kind": "resource_shortage",
      "resource": "corn"
    }
  },
  {
    "id": "connoisseur_boom",
    "title": "Connoisseur boom",
    "effect": "Demand **+3** next round, but the boost only applies to sales of barrels **aged 6+ years**.",
    "deckCopies": 2,
    "resolved": {
      "kind": "conditional_demand_boost",
      "delta": 3,
      "minAge": 6
    }
  },
  {
    "id": "distillery_strike",
    "title": "Distillery strike",
    "effect": "The player with the **most barrels** can't make bourbon next round.",
    "deckCopies": 1,
    "resolved": {
      "kind": "leader_skip_make",
      "criterion": "most_barrels"
    }
  },
  {
    "id": "flood_in_bardstown",
    "title": "Flood in Bardstown",
    "effect": "Every barrel in **Bardstown** loses **1 year** of aging immediately.",
    "deckCopies": 1,
    "resolved": {
      "kind": "rickhouse_age_loss",
      "rickhouseId": "rickhouse-4",
      "loss": 1
    }
  },
  {
    "id": "premium_push",
    "title": "Premium push",
    "effect": "Demand **+2** next round, but only sales that land in the **bill's top demand band** get it.",
    "deckCopies": 2,
    "resolved": {
      "kind": "conditional_demand_boost",
      "delta": 2,
      "topBandOnly": true
    }
  },
  {
    "id": "single_barrel_spotlight",
    "title": "Single-barrel spotlight",
    "effect": "The **first sale** of next round gets demand **+3**; subsequent sales use base demand.",
    "deckCopies": 1,
    "resolved": {
      "kind": "conditional_demand_boost",
      "delta": 3,
      "firstSaleOnly": true
    }
  },
  {
    "id": "speculator_frenzy",
    "title": "Speculator frenzy",
    "effect": "Demand **+3** next round, but every sale drops demand by **2** instead of 1.",
    "deckCopies": 2,
    "resolved": {
      "kind": "persistent_demand_delta",
      "delta": 3,
      "extraRounds": 0
    }
  },
  {
    "id": "speculator_frenzy_decay",
    "title": "Speculator volatility",
    "effect": "The market is jumpy — every sale next round drops demand by **2** instead of 1.",
    "deckCopies": 1,
    "resolved": {
      "kind": "accelerated_demand_decay",
      "perSale": 2
    }
  },
  {
    "id": "wholesaler_crackdown",
    "title": "Wholesaler crackdown",
    "effect": "Player holding the most mash bills must **discard 1**.",
    "deckCopies": 2,
    "resolved": {
      "kind": "leader_discard_bill",
      "criterion": "most_bills"
    }
  },
  {
    "id": "coopers_apprentice",
    "title": "Cooper's apprentice",
    "effect": "Trainees fan out. **All players** draw **1 cask** from the market piles now.",
    "deckCopies": 2,
    "resolved": {
      "kind": "all_draw_resource",
      "resource": "cask",
      "count": 1
    }
  },
  {
    "id": "quiet_quarter",
    "title": "Quiet quarter",
    "effect": "A lull settles in. No mechanical effect — the market simply waits.",
    "deckCopies": 2,
    "resolved": {
      "kind": "flavor"
    }
  }
] as const;

export const MARKET_CARDS_BY_ID: Readonly<Record<string, MarketCardDef>> = Object.freeze(
  Object.fromEntries(MARKET_CARDS.map((c) => [c.id, c] as const))
);
