/**
 * AUTOGENERATED — DO NOT EDIT.
 * Mirrors data/market_cards.yaml for the market-phase deck.
 *
 * (Hand-authored alongside the YAML until scripts/build-catalogs.ts is taught
 * to emit this file too. If you edit one, edit the other.)
 */

import type { MarketCardDef } from "./types";

export const MARKET_CARDS: readonly MarketCardDef[] = [
  {
    id: "holiday_rush",
    title: "Holiday rush",
    effect: "Demand **+2**.",
    deckCopies: 4,
    resolved: { kind: "demand_delta", delta: 2 },
  },
  {
    id: "critic_review",
    title: "Critic's review",
    effect: "Demand **+2**.",
    deckCopies: 3,
    resolved: { kind: "demand_delta", delta: 2 },
  },
  {
    id: "cocktail_revival",
    title: "Cocktail revival",
    effect: "Demand **+1**.",
    deckCopies: 4,
    resolved: { kind: "demand_delta", delta: 1 },
  },
  {
    id: "export_deal",
    title: "Export deal",
    effect: "Demand **+3**.",
    deckCopies: 2,
    resolved: { kind: "demand_delta", delta: 3 },
  },
  {
    id: "bourbon_festival",
    title: "Bourbon festival",
    effect: "Demand **+1**.",
    deckCopies: 3,
    resolved: { kind: "demand_delta", delta: 1 },
  },
  {
    id: "celebrity_endorsement",
    title: "Celebrity endorsement",
    effect: "Demand **+2**.",
    deckCopies: 2,
    resolved: { kind: "demand_delta", delta: 2 },
  },
  {
    id: "distillers_award",
    title: "Distillers' award",
    effect: "Demand **+1**.",
    deckCopies: 3,
    resolved: { kind: "demand_delta", delta: 1 },
  },
  {
    id: "economic_downturn",
    title: "Economic downturn",
    effect: "Demand **-2**.",
    deckCopies: 2,
    resolved: { kind: "demand_delta", delta: -2 },
  },
  {
    id: "wine_takes_over",
    title: "Wine takes over",
    effect: "Demand **-1**.",
    deckCopies: 2,
    resolved: { kind: "demand_delta", delta: -1 },
  },
  {
    id: "corn_shortage",
    title: "Corn shortage",
    effect: "A poor corn harvest tightens supply. (Flavor for now.)",
    deckCopies: 1,
    resolved: { kind: "flavor" },
  },
  {
    id: "rickhouse_inspection",
    title: "Rickhouse inspection",
    effect: "Inspectors comb the warehouses. (Flavor for now.)",
    deckCopies: 1,
    resolved: { kind: "flavor" },
  },
  {
    id: "trade_show_buzz",
    title: "Trade show buzz",
    effect: "Demand **+1**.",
    deckCopies: 2,
    resolved: { kind: "demand_delta", delta: 1 },
  },
];

export const MARKET_CARDS_BY_ID: Readonly<Record<string, MarketCardDef>> =
  Object.fromEntries(MARKET_CARDS.map((c) => [c.id, c] as const));
