/**
 * AUTOGENERATED — DO NOT EDIT.
 * Regenerated by scripts/build-catalogs.ts from data/*.yaml.
 */

import type { OperationsCardDef } from "./types";

export const OPERATIONS_CARDS: readonly OperationsCardDef[] = [
  {
    "id": "county_rebate",
    "categoryId": "cash_liquidity",
    "title": "County rebate",
    "concept": "Economic development grant.",
    "effect": "Gain **$6** if market demand is **≥ 6**; otherwise gain **$2**. *(Rough EV ≈ $4 if high-demand happens ~half the time—tune with your demand model.)*"
  },
  {
    "id": "fire_sale",
    "categoryId": "cash_liquidity",
    "title": "Fire sale",
    "concept": "Move inventory fast.",
    "effect": "Discard **1 resource**; gain **$6**. *(Treat net as **~$5** if a spare resource is worth ~$1.)*"
  },
  {
    "id": "angels_share_cash",
    "categoryId": "cash_liquidity",
    "title": "Angels' share (cash)",
    "concept": "Evaporation in your favor.",
    "effect": "Gain **$2** per **year token** on your **oldest** barrelled bourbon (**max $10**). *(Typical **1–2** tokens → median-friendly; cap stops runaway tail on this card—tail lives elsewhere.)*"
  },
  {
    "id": "tour_bus_tips",
    "categoryId": "cash_liquidity",
    "title": "Tour bus tips",
    "concept": "Visitors love the gift shop.",
    "effect": "Gain **$3** **+$1** per **distinct rickhouse** where you have at least one barrel (**max $3 + 6**). *(Median case **~$4–$5** with **1–2** houses; **right tail** when you span many regions.)*"
  },
  {
    "id": "stack_swap",
    "categoryId": "rickhouse_fees",
    "title": "Stack swap",
    "concept": "Crew rotates barrels for you.",
    "effect": "Add **+1 year token** to one of your barrelled bourbons (no fee paid)."
  },
  {
    "id": "cooper_on_call",
    "categoryId": "market_hand",
    "title": "Cooper on call",
    "concept": "Emergency repair staves.",
    "effect": "Swap a cask in one of your rickhouses for a cask in your hand."
  },
  {
    "id": "mulligan_mash",
    "categoryId": "market_hand",
    "title": "Mulligan mash",
    "concept": "Scrap the cook.",
    "effect": "**Discard up to 2** resources; **draw 4** from any combination of piles. **Gain $3** from scrap credit."
  },
  {
    "id": "grain_sweep",
    "categoryId": "market_hand",
    "title": "Grain sweep",
    "concept": "Clean the bin.",
    "effect": "Take **2** cards from the **Grain** pile; **gain $2**. *(Roughly **~$4** equivalent if a card ≈ **$1**.)*"
  },
  {
    "id": "corn_rush",
    "categoryId": "market_hand",
    "title": "Corn rush",
    "concept": "Harvest window.",
    "effect": "Take **2** cards from the **Corn** pile; **gain $2**. *(Same as above.)*"
  },
  {
    "id": "sample_pour",
    "categoryId": "bourbon_sale_moment",
    "title": "Sample pour",
    "concept": "Small loss, good will.",
    "effect": "**Gain $3** now. On your **next** sale this turn, take **−$1** revenue **but** **market demand** does **not** drop for that sale. *(Net swing depends on sale size—often **~$3** floor.)*"
  },
  {
    "id": "flash_tasting",
    "categoryId": "bourbon_sale_moment",
    "title": "Flash tasting",
    "concept": "Hype before the deal.",
    "effect": "**Gain $2** now. On your **next sale this turn**, treat demand as **+1** for **price lookup only**."
  },
  {
    "id": "broker_call",
    "categoryId": "bourbon_sale_moment",
    "title": "Broker call",
    "concept": "Better quote.",
    "effect": "On your **next sale this turn**, after you see Bourbon Card options, you may **discard 1** resource to **draw 1** replacement Bourbon Card from the deck. **Gain $2** when you sell (even if you don't replace)."
  },
  {
    "id": "sticker_shock",
    "categoryId": "bourbon_sale_moment",
    "title": "Sticker shock",
    "concept": "Customer pays more anyway.",
    "effect": "On your **next sale this turn**, **+$4** revenue; **market demand** still drops normally. *(Tail when your sale price was already high.)*"
  },
  {
    "id": "county_fair_booth",
    "categoryId": "soft_interaction",
    "title": "County fair booth",
    "concept": "Everyone sells a little.",
    "effect": "Each player gains **$1**; you **gain $3** more (**$4** total to you)."
  },
  {
    "id": "smoke_break",
    "categoryId": "cleanup_recovery",
    "title": "Smoke break",
    "concept": "Pause the line.",
    "effect": "**End your action phase now**; **gain $3** if you already took **3+** actions this turn, otherwise **gain $1**."
  },
  {
    "id": "distillers_bonus",
    "categoryId": "new_arrivals",
    "title": "Distiller's bonus",
    "concept": "End-of-year payout.",
    "effect": "**Gain $1 per barrelled bourbon** you own (max $8). *(Steady-scaling payout — rewards mid-game volume.)*"
  },
  {
    "id": "speakeasy_tipoff",
    "categoryId": "new_arrivals",
    "title": "Speakeasy tipoff",
    "concept": "Back-alley intel.",
    "effect": "**Gain $4** if **market demand ≥ 4**, otherwise **gain $1**. Low-variance fallback card."
  },
  {
    "id": "copper_salvage",
    "categoryId": "new_arrivals",
    "title": "Copper salvage",
    "concept": "Pull a barrel out and recoup scrap.",
    "effect": "**Gain $2 per year token** on your *youngest* barrelled bourbon (max **$6**). *(Rewards freshly-laid stock.)*"
  },
  {
    "id": "blenders_touch",
    "categoryId": "new_arrivals",
    "title": "Blender's touch",
    "concept": "Master blender moment.",
    "effect": "**Gain $3** immediately. If you own any barrel whose mash includes **≥3 grain types**, **gain $5** instead."
  },
  {
    "id": "late_shipment",
    "categoryId": "new_arrivals",
    "title": "Late shipment",
    "concept": "A pallet of resources turns up at the gate.",
    "effect": "**Draw 2 resource cards** from a single pile of your choice (face-down). Free — does not cost an additional action."
  },
  {
    "id": "coopers_gift",
    "categoryId": "new_arrivals",
    "title": "Cooper's gift",
    "concept": "Spare cask from the cooperage.",
    "effect": "**Gain $2**. If you have **fewer than 2 barrels** barrelled, **gain $4** instead. A mercy payout for slow starts."
  },
  {
    "id": "state_fair_demo",
    "categoryId": "new_arrivals",
    "title": "State fair demo",
    "concept": "Public tasting pays the gate.",
    "effect": "**Gain $6** if market demand is **odd**, otherwise **gain $3**. Demand-parity flex."
  },
  {
    "id": "insurance_payout",
    "categoryId": "new_arrivals",
    "title": "Insurance payout",
    "concept": "Claim settled.",
    "effect": "**Gain $2 per rickhouse** where you have **no barrels** (max **$6**). *(Awkward-comeback tool — pays more when you're thin.)*"
  }
] as const;

export const OPERATIONS_CARDS_BY_ID: Readonly<Record<string, OperationsCardDef>> = Object.freeze(
  Object.fromEntries(OPERATIONS_CARDS.map((c) => [c.id, c]))
);
