/**
 * AUTOGENERATED — DO NOT EDIT.
 * Regenerated by scripts/build-catalogs.ts from data/*.yaml.
 */

import type { ResourceCardDef } from "./types";

export const SPECIALTY_RESOURCES: readonly ResourceCardDef[] = [
  {
    "id": "new_american_oak",
    "name": "New American oak",
    "categoryId": "cask_specialty",
    "hook": "Big vanilla, first fill.",
    "rule": "When you **sell** bourbon that included this cask in the mash, **+$1** revenue once.",
    "play": {
      "resource": "cask",
      "engine": "modeled",
      "on_sell": [
        {
          "op": "revenue_bonus",
          "amount": 1,
          "limit": "once_per_sale"
        }
      ]
    }
  },
  {
    "id": "heavy_char",
    "name": "Heavy char",
    "categoryId": "cask_specialty",
    "hook": "Deep toast layer.",
    "rule": "Treat this cask as **+1** toward **award** thresholds that care about “quality” or char (if you use tiers).",
    "play": {
      "resource": "cask",
      "engine": "pending",
      "flags": [
        "award_quality_plus_1_unimplemented"
      ]
    }
  },
  {
    "id": "second_use_barrel",
    "name": "Second-use barrel",
    "categoryId": "cask_specialty",
    "hook": "Softer oak.",
    "rule": "**−$1** to **entry rent** the first time you **barrel** the bourbon made with this cask (this placement only).",
    "play": {
      "resource": "cask",
      "engine": "modeled",
      "on_make_bourbon": [
        {
          "op": "barrel_entry_rent_discount",
          "amount": -1,
          "limit": "first_barrel_placement_from_mash"
        }
      ]
    }
  },
  {
    "id": "honey_barrel",
    "name": "Honey barrel",
    "categoryId": "cask_specialty",
    "hook": "Prior honey holds sweetness.",
    "rule": "On **sell**, you may treat **market demand** as **+1** for **price lookup only** (once).",
    "play": {
      "resource": "cask",
      "engine": "modeled",
      "on_sell": [
        {
          "op": "demand_lookup_shift",
          "delta": 1,
          "limit": "once_per_sale"
        }
      ]
    }
  },
  {
    "id": "wine_finish_cask",
    "name": "Wine finish cask",
    "categoryId": "cask_specialty",
    "hook": "Red-wine staves.",
    "rule": "When you **sell**, draw **+1** Bourbon Card (then choose as usual) **once** if your mash had **≥2** grains.",
    "play": {
      "resource": "cask",
      "engine": "modeled",
      "on_sell": [
        {
          "op": "draw_bourbon_cards",
          "count": 1,
          "limit": "once_per_sale",
          "when": {
            "mash_small_grain_count_gte": 2
          }
        }
      ]
    }
  },
  {
    "id": "small_format",
    "name": "Small format",
    "categoryId": "cask_specialty",
    "hook": "Faster extraction.",
    "rule": "When **aging** would add **1** year token, you may add **2** instead **once** (then flip this card sideways or discard—your call when balancing).",
    "play": {
      "resource": "cask",
      "engine": "modeled",
      "on_age_tick": [
        {
          "op": "bonus_age_tokens",
          "extra": 1,
          "limit": "once_per_barrel"
        }
      ]
    }
  },
  {
    "id": "large_format",
    "name": "Large format",
    "categoryId": "cask_specialty",
    "hook": "Slower, rounder.",
    "rule": "**−$1** **rickhouse fee** for the rickhouse where this bourbon sits **once per turn** while this barrel is there (max **$1**).",
    "play": {
      "resource": "cask",
      "engine": "modeled",
      "on_rickhouse_fee": [
        {
          "op": "rickhouse_fee_discount",
          "amount": -1,
          "limit": "each_turn_while_barrel_in_rickhouse",
          "max_per_turn": 1
        }
      ]
    }
  },
  {
    "id": "independent_stave",
    "name": "Independent stave",
    "categoryId": "cask_specialty",
    "hook": "Tight grain, pricey.",
    "rule": "**Trade** only: this cask counts as **$2** toward trades where you value resources in **$** (if you use that optional rule).",
    "play": {
      "resource": "cask",
      "engine": "pending",
      "on_trade": [
        {
          "op": "legacy_manual",
          "note": "Trade valuation only"
        }
      ]
    }
  },
  {
    "id": "cooper_s_select",
    "name": "Cooper’s select",
    "categoryId": "cask_specialty",
    "hook": "Hand-checked.",
    "rule": "**Once** when you **make bourbon**, you may **look** at the top **Bourbon Card** after you commit the mash.",
    "play": {
      "resource": "cask",
      "engine": "pending",
      "on_make_bourbon": [
        {
          "op": "legacy_manual",
          "note": "Peek top bourbon card"
        }
      ]
    }
  },
  {
    "id": "leaky_angel",
    "name": "Leaky angel",
    "categoryId": "cask_specialty",
    "hook": "Evaporation story.",
    "rule": "On **sell**, **+$1** revenue; **−$1** revenue if **market demand** is **0** (risk/reward).",
    "play": {
      "resource": "cask",
      "engine": "partial",
      "on_sell": [
        {
          "op": "revenue_bonus",
          "amount": 1,
          "limit": "once_per_sale"
        },
        {
          "op": "revenue_bonus",
          "amount": -1,
          "limit": "once_per_sale",
          "when": {
            "demand_lte": 0
          }
        }
      ]
    }
  },
  {
    "id": "yellow_dent_2",
    "name": "Yellow dent #2",
    "categoryId": "corn_specialty",
    "hook": "Workhorse feed corn.",
    "rule": "No extra rule—this is the **baseline** specialty (vanilla flavor text only).",
    "play": {
      "resource": "corn",
      "engine": "modeled",
      "on_sell": [
        {
          "op": "noop"
        }
      ]
    }
  },
  {
    "id": "heirloom_blue",
    "name": "Heirloom blue",
    "categoryId": "corn_specialty",
    "hook": "Terroir flex.",
    "rule": "**Silver**-related award checks treat **one** fewer matching symbol **once** when this corn is in the mash (if you use symbol checks).",
    "play": {
      "resource": "corn",
      "engine": "pending",
      "flags": [
        "silver_symbol_easier_unimplemented"
      ]
    }
  },
  {
    "id": "bourbon_grade_bulk",
    "name": "Bourbon-grade bulk",
    "categoryId": "corn_specialty",
    "hook": "Volume play.",
    "rule": "If this mash uses **3** corn cards, **+$2** on **sell**; if **1** corn, **+$0**.",
    "play": {
      "resource": "corn",
      "engine": "modeled",
      "on_sell": [
        {
          "op": "revenue_bonus",
          "amount": 2,
          "limit": "once_per_sale",
          "when": {
            "mash_corn_count_eq": 3
          }
        }
      ]
    }
  },
  {
    "id": "high_starch_hybrid",
    "name": "High-starch hybrid",
    "categoryId": "corn_specialty",
    "hook": "Fermentation yield.",
    "rule": "On **make bourbon**, **gain $1** from the bank (once per mash that uses this card).",
    "play": {
      "resource": "corn",
      "engine": "modeled",
      "on_make_bourbon": [
        {
          "op": "bank_payout",
          "amount": 1,
          "limit": "once_per_mash"
        }
      ]
    }
  },
  {
    "id": "local_co_op_corn",
    "name": "Local co-op corn",
    "categoryId": "corn_specialty",
    "hook": "Story for tourists.",
    "rule": "On **sell**, if **≥2** other players have barrelled bourbon this game, **+$1** revenue.",
    "play": {
      "resource": "corn",
      "engine": "modeled",
      "on_sell": [
        {
          "op": "revenue_bonus",
          "amount": 1,
          "limit": "once_per_sale",
          "when": {
            "other_barons_barrelled_gte": 2
          }
        }
      ]
    }
  },
  {
    "id": "drought_year",
    "name": "Drought year",
    "categoryId": "corn_specialty",
    "hook": "Scarce, intense.",
    "rule": "On **sell**, **+$2** revenue if **market demand ≤ 3**; otherwise **+$0**.",
    "play": {
      "resource": "corn",
      "engine": "modeled",
      "on_sell": [
        {
          "op": "revenue_bonus",
          "amount": 2,
          "limit": "once_per_sale",
          "when": {
            "demand_lte": 3
          }
        }
      ]
    }
  },
  {
    "id": "waxy_corn",
    "name": "Waxy corn",
    "categoryId": "corn_specialty",
    "hook": "Unusual mouthfeel lab.",
    "rule": "When you **sell**, you may **discard 1** resource to **draw 1** Bourbon Card (then choose as usual).",
    "play": {
      "resource": "corn",
      "engine": "pending",
      "on_sell": [
        {
          "op": "legacy_manual",
          "note": "Discard resource then draw bourbon"
        }
      ]
    }
  },
  {
    "id": "two_row_malt",
    "name": "Two-row malt",
    "categoryId": "barley_specialty",
    "hook": "Standard malted barley.",
    "rule": "**Once** on **sell**, treat your bourbon’s **age** as **+1** for **Market Price Guide** only.",
    "play": {
      "resource": "barley",
      "engine": "modeled",
      "on_sell": [
        {
          "op": "age_lookup_shift_years",
          "years": 1,
          "limit": "once_per_sale"
        }
      ]
    }
  },
  {
    "id": "six_row_spice",
    "name": "Six-row spice",
    "categoryId": "barley_specialty",
    "hook": "Grainy, sharp.",
    "rule": "If your mash also includes **rye**, **+$1** on **sell**.",
    "play": {
      "resource": "barley",
      "engine": "modeled",
      "on_sell": [
        {
          "op": "revenue_bonus",
          "amount": 1,
          "limit": "once_per_sale",
          "when": {
            "mash_includes_rye": true
          }
        }
      ]
    }
  },
  {
    "id": "peated_malt",
    "name": "Peated malt",
    "categoryId": "barley_specialty",
    "hook": "Smoke note.",
    "rule": "**Gold**-related checks: treat **one** requirement as satisfied if you also spent **+$0**—tune to your Gold card text (placeholder: **+1** “smoke” icon).",
    "play": {
      "resource": "barley",
      "engine": "pending",
      "flags": [
        "gold_easier_unimplemented"
      ]
    }
  },
  {
    "id": "chocolate_malt",
    "name": "Chocolate malt",
    "categoryId": "barley_specialty",
    "hook": "Color and cocoa notes.",
    "rule": "On **sell**, if **market demand** is **even**, **+$1** revenue (ties to your **Notes** on even demand).",
    "play": {
      "resource": "barley",
      "engine": "modeled",
      "on_sell": [
        {
          "op": "revenue_bonus",
          "amount": 1,
          "limit": "once_per_sale",
          "when": {
            "demand_even": true
          }
        }
      ]
    }
  },
  {
    "id": "high_rye_bite",
    "name": "High-rye bite",
    "categoryId": "rye_specialty",
    "hook": "Spice forward.",
    "rule": "On **sell**, **+$1** revenue if **market demand ≥ 6**.",
    "play": {
      "resource": "rye",
      "engine": "modeled",
      "on_sell": [
        {
          "op": "revenue_bonus",
          "amount": 1,
          "limit": "once_per_sale",
          "when": {
            "demand_gte": 6
          }
        }
      ]
    }
  },
  {
    "id": "malted_rye",
    "name": "Malted rye",
    "categoryId": "rye_specialty",
    "hook": "Softer spice.",
    "rule": "**−$1** to **rickhouse fee** for **one** rickhouse where this barrel sits **this turn** (once).",
    "play": {
      "resource": "rye",
      "engine": "partial",
      "on_rickhouse_fee": [
        {
          "op": "rickhouse_fee_discount",
          "amount": -1,
          "limit": "each_turn_while_barrel_in_rickhouse",
          "max_per_turn": 1
        }
      ]
    }
  },
  {
    "id": "canadian_style_rye",
    "name": "Canadian-style rye",
    "categoryId": "rye_specialty",
    "hook": "Label story.",
    "rule": "On **trade**, you may swap this card for **any one** grain card from a willing player **without** using an extra action (still follow trade timing rules).",
    "play": {
      "resource": "rye",
      "engine": "pending",
      "on_trade": [
        {
          "op": "legacy_manual",
          "note": "Free-action grain swap on trade"
        }
      ]
    }
  },
  {
    "id": "soft_red_winter",
    "name": "Soft red winter",
    "categoryId": "wheat_specialty",
    "hook": "Easy, sweet.",
    "rule": "On **sell**, **+$1** revenue if your mash has **exactly 2** total grain cards (barley/rye/wheat).",
    "play": {
      "resource": "wheat",
      "engine": "modeled",
      "on_sell": [
        {
          "op": "revenue_bonus",
          "amount": 1,
          "limit": "once_per_sale",
          "when": {
            "mash_small_grain_count_eq": 2
          }
        }
      ]
    }
  },
  {
    "id": "wheated_bill_helper",
    "name": "Wheated bill helper",
    "categoryId": "wheat_specialty",
    "hook": "Wheater identity.",
    "rule": "If your mash has **no rye**, treat **demand** as **+1** for **price lookup** on **sell** (once).",
    "play": {
      "resource": "wheat",
      "engine": "modeled",
      "on_sell": [
        {
          "op": "demand_lookup_shift",
          "delta": 1,
          "limit": "once_per_sale",
          "when": {
            "mash_excludes_rye": true
          }
        }
      ]
    }
  },
  {
    "id": "creamy_wheat",
    "name": "Creamy wheat",
    "categoryId": "wheat_specialty",
    "hook": "Mouthfeel marketing.",
    "rule": "When you **sell**, you may **ignore** **−$1** revenue from **one** operations effect this turn (if applicable).",
    "play": {
      "resource": "wheat",
      "engine": "pending",
      "on_sell": [
        {
          "op": "legacy_manual",
          "note": "Negate -$1 from one operations effect this turn"
        }
      ]
    }
  },
  {
    "id": "certified_organic_grain",
    "name": "Certified organic grain",
    "categoryId": "cross_type_rare_promos_optional",
    "hook": "Paper trail.",
    "rule": "On **sell**, **+$1**; **−$1** on **sell** if **market demand** is **odd** (if you track odd/even quirks).",
    "play": {
      "resource": "multi",
      "engine": "partial",
      "on_sell": [
        {
          "op": "revenue_bonus",
          "amount": 1,
          "limit": "once_per_sale"
        },
        {
          "op": "revenue_bonus",
          "amount": -1,
          "limit": "once_per_sale",
          "when": {
            "demand_odd": true
          }
        }
      ]
    }
  },
  {
    "id": "heritage_grist",
    "name": "Heritage grist",
    "categoryId": "cross_type_rare_promos_optional",
    "hook": "Pre-mixed bill.",
    "rule": "Occupies **two** of your four **corn+grain** slots **by itself**; **+1** Bourbon Card draw on **sell** (then choose as usual).",
    "play": {
      "resource": "multi",
      "grain_slot_cost": 2,
      "engine": "modeled",
      "flags": [
        "counts_as_corn_and_one_grain"
      ],
      "on_sell": [
        {
          "op": "draw_bourbon_cards",
          "count": 1,
          "limit": "once_per_sale"
        }
      ]
    }
  },
  {
    "id": "neutral_spirits_transfer",
    "name": "Neutral spirits transfer",
    "categoryId": "cross_type_rare_promos_optional",
    "hook": "Blending loophole.",
    "rule": "**Bottled-in-Bond only** (if you want): may **combine** with another barrel in the same rickhouse for **one** merged **sell** (tune carefully).",
    "play": {
      "resource": "cask",
      "engine": "pending",
      "flags": [
        "bib_merge_sell_unimplemented"
      ]
    }
  },
  {
    "id": "charter_floor_myth",
    "name": "Charter floor myth",
    "categoryId": "strong_special_tier_a",
    "hook": "Legendary lease deal.",
    "rule": "While this barrel is in a rickhouse, **ignore rickhouse fees** for **this barrel only** (still pay other barrels normally).",
    "play": {
      "resource": "cask",
      "engine": "partial",
      "flags": [
        "ignore_rickhouse_fees_this_barrel_unimplemented"
      ],
      "on_rickhouse_fee": [
        {
          "op": "legacy_manual",
          "note": "Ignore per-barrel rent for this mash’s barrel only"
        }
      ]
    }
  },
  {
    "id": "ten_year_tale",
    "name": "Ten-year tale",
    "categoryId": "strong_special_tier_a",
    "hook": "Tasting-room story sells.",
    "rule": "On **sell**, **+$4** revenue **once** if **market demand ≥ 6**.",
    "play": {
      "resource": "rye",
      "engine": "modeled",
      "on_sell": [
        {
          "op": "revenue_bonus",
          "amount": 4,
          "limit": "once_per_sale",
          "when": {
            "demand_gte": 6
          }
        }
      ]
    }
  },
  {
    "id": "limestone_ledger_age",
    "name": "Limestone ledger age",
    "categoryId": "strong_special_tier_a",
    "hook": "Accounting fiction, real smoothness.",
    "rule": "On **sell**, treat bourbon **age** as **+2** for **Market Price Guide** lookup only **once**.",
    "play": {
      "resource": "wheat",
      "engine": "modeled",
      "on_sell": [
        {
          "op": "age_lookup_shift_years",
          "years": 2,
          "limit": "once_per_sale"
        }
      ]
    }
  },
  {
    "id": "headline_pour",
    "name": "Headline pour",
    "categoryId": "global_swing_tier_b",
    "hook": "Viral pour event.",
    "rule": "After this **sell** resolves, **market demand** increases by **+1** (clamp **0–12**) **once**.",
    "play": {
      "resource": "corn",
      "engine": "modeled",
      "on_sell": [
        {
          "op": "market_demand_global_delta",
          "delta": 1,
          "limit": "once_per_sale"
        }
      ]
    }
  },
  {
    "id": "tariff_whisper",
    "name": "Tariff whisper",
    "categoryId": "global_swing_tier_b",
    "hook": "Buyers flinch.",
    "rule": "After this **sell** resolves, **market demand** decreases by **1** (clamp **0–12**) **once**.",
    "play": {
      "resource": "barley",
      "engine": "modeled",
      "on_sell": [
        {
          "op": "market_demand_global_delta",
          "delta": -1,
          "limit": "once_per_sale"
        }
      ]
    }
  },
  {
    "id": "wet_warehouse_floor",
    "name": "Wet warehouse floor",
    "categoryId": "detrimental_soft",
    "hook": "Leak story — buyers hesitate.",
    "rule": "On **sell**, this bourbon’s proceeds are **−$2** after the Market Price Guide (minimum **$0** total from this sale before action fees).",
    "play": {
      "resource": "corn",
      "engine": "modeled",
      "on_sell": [
        {
          "op": "revenue_bonus",
          "amount": -2,
          "limit": "once_per_sale"
        }
      ]
    }
  },
  {
    "id": "green_grain_day",
    "name": "Green grain day",
    "categoryId": "detrimental_soft",
    "hook": "Off-profile cut.",
    "rule": "On **sell**, **−$1** revenue **once** (still playable — hedge with wheat specials).",
    "play": {
      "resource": "rye",
      "engine": "modeled",
      "on_sell": [
        {
          "op": "revenue_bonus",
          "amount": -1,
          "limit": "once_per_sale"
        }
      ]
    }
  }
] as unknown as readonly ResourceCardDef[];

export const SPECIALTY_RESOURCES_BY_ID: Readonly<Record<string, ResourceCardDef>> = Object.freeze(
  Object.fromEntries(SPECIALTY_RESOURCES.map((c) => [c.id, c]))
);
