/**
 * Build step: read data/*.yaml and emit typed lib/catalogs/*.generated.ts files.
 * Run via `npm run build:catalogs` (also runs automatically before `dev` and `build`).
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import YAML from "yaml";

const ROOT = process.cwd();
const DATA = resolve(ROOT, "data");
const OUT = resolve(ROOT, "lib/catalogs");
mkdirSync(OUT, { recursive: true });

type YamlAny = Record<string, unknown>;

function loadYaml(file: string): YamlAny {
  const text = readFileSync(resolve(DATA, file), "utf8");
  return YAML.parse(text) as YamlAny;
}

function writeTs(file: string, contents: string) {
  const header = `/**
 * AUTOGENERATED — DO NOT EDIT.
 * Regenerated by scripts/build-catalogs.ts from data/*.yaml.
 */

`;
  writeFileSync(resolve(OUT, file), header + contents, "utf8");
  console.log(`wrote ${file}`);
}

// ---------- Bourbon cards ----------

function buildBourbon() {
  const doc = loadYaml("bourbon_cards.yaml");
  type RecipeBound = { min?: number; max?: number };
  type Recipe = {
    corn?: RecipeBound;
    barley?: RecipeBound;
    rye?: RecipeBound;
    wheat?: RecipeBound;
    grain?: RecipeBound;
  };
  const cards = doc.cards as Array<{
    id: string;
    name: string;
    rarity: string;
    grid: number[][];
    awards: { silver?: string; gold?: string } | null;
    brandValue?: number;
    recipe?: Recipe;
  }>;

  const recipeKeys = new Set([
    "corn",
    "barley",
    "rye",
    "wheat",
    "grain",
  ]);
  for (const c of cards) {
    if (c.grid.length !== 3 || c.grid.some((row) => row.length !== 3)) {
      throw new Error(`Bourbon card ${c.id} has malformed grid`);
    }
    if (c.rarity !== "Standard" && c.rarity !== "Rare") {
      throw new Error(`Bourbon card ${c.id} unknown rarity: ${c.rarity}`);
    }
    if (c.recipe) {
      for (const k of Object.keys(c.recipe)) {
        if (!recipeKeys.has(k)) {
          throw new Error(
            `Bourbon card ${c.id} has unknown recipe key '${k}' (expected corn / barley / rye / wheat / grain)`,
          );
        }
      }
    }
    // Default brandValue for Gold-capable cards: grid maximum + a small
    // rarity bonus, rounded up to the nearest $5 so the trophy value
    // visually scales with the card's strength. Cards without a Gold
    // award never become trophies, so they don't get a brandValue.
    if (c.awards && c.awards.gold && typeof c.brandValue !== "number") {
      const gridMax = Math.max(...c.grid.flatMap((row) => row));
      const rarityBonus = c.rarity === "Rare" ? 10 : 5;
      const raw = gridMax + rarityBonus;
      c.brandValue = Math.ceil(raw / 5) * 5;
    }
  }

  const body =
    `import type { BourbonCardDef } from "./types";\n\n` +
    `export const BOURBON_CARDS: readonly BourbonCardDef[] = ${JSON.stringify(cards, null, 2)} as const;\n\n` +
    `export const BOURBON_CARDS_BY_ID: Readonly<Record<string, BourbonCardDef>> = Object.freeze(\n` +
    `  Object.fromEntries(BOURBON_CARDS.map((c) => [c.id, c]))\n` +
    `);\n`;

  writeTs("bourbon.generated.ts", body);
}

// ---------- Investment cards ----------

function buildInvestment() {
  const doc = loadYaml("investment_catalog.yaml");
  const cards = doc.cards as Array<{
    id: string;
    name: string;
    rarity: string;
    capital: number;
    short: string;
    effect: string;
    deckCopies: number;
    modifiers: Array<Record<string, unknown>>;
  }>;

  for (const c of cards) {
    if (typeof c.capital !== "number") {
      throw new Error(`Investment ${c.id} missing capital`);
    }
    for (const m of c.modifiers ?? []) {
      const kind = m.kind as string;
      if (
        kind !== "rickhouse_fee_discount" &&
        kind !== "action_cost_discount" &&
        kind !== "market_buy_bonus_cards"
      ) {
        throw new Error(`Investment ${c.id} unknown modifier kind: ${kind}`);
      }
    }
  }

  const body =
    `import type { InvestmentCardDef } from "./types";\n\n` +
    `export const INVESTMENT_CARDS: readonly InvestmentCardDef[] = ${JSON.stringify(cards, null, 2)} as const;\n\n` +
    `export const INVESTMENT_CARDS_BY_ID: Readonly<Record<string, InvestmentCardDef>> = Object.freeze(\n` +
    `  Object.fromEntries(INVESTMENT_CARDS.map((c) => [c.id, c]))\n` +
    `);\n`;

  writeTs("investment.generated.ts", body);
}

// ---------- Operations cards ----------

function buildOperations() {
  const doc = loadYaml("operations_cards.yaml");
  const categories = doc.categories as Array<{
    id: string;
    title: string;
    cards: Array<{ id: string; title: string; concept: string; effect: string }>;
  }>;

  type Out = {
    id: string;
    categoryId: string;
    title: string;
    concept: string;
    effect: string;
  };
  const flat: Out[] = [];
  for (const cat of categories) {
    for (const c of cat.cards) {
      flat.push({
        id: c.id,
        categoryId: cat.id,
        title: c.title,
        concept: c.concept,
        effect: c.effect,
      });
    }
  }

  const body =
    `import type { OperationsCardDef } from "./types";\n\n` +
    `export const OPERATIONS_CARDS: readonly OperationsCardDef[] = ${JSON.stringify(flat, null, 2)} as const;\n\n` +
    `export const OPERATIONS_CARDS_BY_ID: Readonly<Record<string, OperationsCardDef>> = Object.freeze(\n` +
    `  Object.fromEntries(OPERATIONS_CARDS.map((c) => [c.id, c]))\n` +
    `);\n`;

  writeTs("operations.generated.ts", body);
}

// ---------- Resource cards (specialty) ----------

function buildResources() {
  const doc = loadYaml("resource_cards.yaml");
  const categories = doc.categories as Array<{
    id: string;
    title: string;
    cards: Array<{
      id: string;
      name: string;
      hook?: string;
      rule: string;
      play: Record<string, unknown>;
    }>;
  }>;

  type Out = {
    id: string;
    name: string;
    categoryId: string;
    hook?: string;
    rule: string;
    play: Record<string, unknown>;
  };
  const flat: Out[] = [];
  for (const cat of categories) {
    for (const c of cat.cards) {
      flat.push({
        id: c.id,
        name: c.name,
        categoryId: cat.id,
        hook: c.hook,
        rule: c.rule,
        play: c.play,
      });
    }
  }

  const body =
    `import type { ResourceCardDef } from "./types";\n\n` +
    `export const SPECIALTY_RESOURCES: readonly ResourceCardDef[] = ${JSON.stringify(flat, null, 2)} as unknown as readonly ResourceCardDef[];\n\n` +
    `export const SPECIALTY_RESOURCES_BY_ID: Readonly<Record<string, ResourceCardDef>> = Object.freeze(\n` +
    `  Object.fromEntries(SPECIALTY_RESOURCES.map((c) => [c.id, c]))\n` +
    `);\n`;

  writeTs("resource.generated.ts", body);
}

// ---------- Main ----------

buildBourbon();
buildInvestment();
buildOperations();
buildResources();

console.log("catalog build complete");
