/**
 * Build step: read data/*.yaml and emit typed lib/catalogs/*.generated.ts files.
 * Run via `npm run build:catalogs` (also runs automatically before `dev` and `build`).
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import YAML from "yaml";

const ROOT = process.cwd();
const DATA = resolve(ROOT, "data");
const OUT = resolve(ROOT, "lib/catalogs");
mkdirSync(OUT, { recursive: true });

type YamlAny = Record<string, unknown>;

function loadYaml(file: string): YamlAny {
  const text = readFileSync(resolve(DATA, file), "utf8");
  return YAML.parse(text) as YamlAny;
}

function writeTs(file: string, contents: string) {
  const header = `/**
 * AUTOGENERATED — DO NOT EDIT.
 * Regenerated by scripts/build-catalogs.ts from data/*.yaml.
 */

`;
  writeFileSync(resolve(OUT, file), header + contents, "utf8");
  console.log(`wrote ${file}`);
}

// ---------- Bourbon cards ----------

function buildBourbon() {
  const doc = loadYaml("bourbon_cards.yaml");
  type RecipeBound = { min?: number; max?: number };
  type Recipe = {
    corn?: RecipeBound;
    barley?: RecipeBound;
    rye?: RecipeBound;
    wheat?: RecipeBound;
    grain?: RecipeBound;
  };
  type Bands = number[];
  type Tier = "common" | "uncommon" | "rare" | "epic" | "legendary";
  const cards = doc.cards as Array<{
    id: string;
    name: string;
    slogan?: string;
    description?: string;
    rarity: string;
    ageBands?: Bands;
    demandBands?: Bands;
    grid: number[][];
    awards: { silver?: string; gold?: string } | null;
    brandValue?: number;
    recipe?: Recipe;
    tier?: Tier;
  }>;

  // Per-tier MAX grid dimensions [maxAgeBands, maxDemandBands]. Common
  // bills are deliberately simple (2×2 ceiling) so the workhorse cards
  // present a small number of market states; rarer tiers earn the right
  // to a richer pricing surface.
  const MAX_GRID_BY_TIER: Record<Tier, [number, number]> = {
    common: [2, 2],
    uncommon: [2, 3],
    rare: [3, 3],
    epic: [3, 3],
    legendary: [3, 3],
  };

  /**
   * Auto-derive the visual tier from grid max + awards when the YAML
   * doesn't override. Tuned against the post-rebalance pool: workhorse
   * bills (max ~$6) land Uncommon, mid-tier (max ~$10) Rare, premium
   * (max ~$15+) Epic, the few Gold-capable flagships ≥$20 Legendary.
   */
  function deriveTier(c: {
    grid: number[][];
    awards: { silver?: string; gold?: string } | null;
  }): Tier {
    const gridMax = Math.max(...c.grid.flatMap((row) => row));
    const hasGold = !!c.awards?.gold;
    const hasSilver = !!c.awards?.silver;
    if (hasGold && gridMax >= 22) return "legendary";
    if (gridMax >= 18 || (hasGold && gridMax >= 14)) return "epic";
    if (gridMax >= 11 || hasSilver) return "rare";
    if (gridMax >= 7) return "uncommon";
    return "common";
  }

  // Default thresholds for cards that don't declare their own. Reused
  // for any axis still on the legacy 3-band defaults; new cards should
  // size their bands explicitly to match their grid shape.
  const DEFAULT_AGE_BANDS: Bands = [2, 4, 8];
  const DEFAULT_DEMAND_BANDS: Bands = [0, 4, 7];

  function ensureStrictlyIncreasing(label: string, t: Bands, id: string) {
    for (let i = 1; i < t.length; i += 1) {
      if (t[i - 1] >= t[i]) {
        throw new Error(
          `Bourbon card ${id}: ${label} ${JSON.stringify(t)} must be strictly increasing`,
        );
      }
    }
  }

  const recipeKeys = new Set([
    "corn",
    "barley",
    "rye",
    "wheat",
    "grain",
  ]);
  for (const c of cards) {
    if (c.rarity !== "Standard" && c.rarity !== "Rare") {
      throw new Error(`Bourbon card ${c.id} unknown rarity: ${c.rarity}`);
    }
    // Per-bill bands. Default for cards that don't (yet) declare their
    // own thresholds; the validator then enforces shape + monotonicity.
    if (!c.ageBands) c.ageBands = [...DEFAULT_AGE_BANDS];
    if (!c.demandBands) c.demandBands = [...DEFAULT_DEMAND_BANDS];
    if (c.ageBands.length < 1 || c.ageBands.length > 3) {
      throw new Error(`Bourbon card ${c.id}: ageBands length must be 1–3`);
    }
    if (c.demandBands.length < 1 || c.demandBands.length > 3) {
      throw new Error(`Bourbon card ${c.id}: demandBands length must be 1–3`);
    }
    if (c.ageBands[0] < 2) {
      throw new Error(
        `Bourbon card ${c.id}: ageBands[0] is ${c.ageBands[0]} but must be ≥ 2 (global "≥2y to sell" floor)`,
      );
    }
    if (c.demandBands[0] < 0) {
      throw new Error(
        `Bourbon card ${c.id}: demandBands[0] is ${c.demandBands[0]} but must be ≥ 0`,
      );
    }
    ensureStrictlyIncreasing("ageBands", c.ageBands, c.id);
    ensureStrictlyIncreasing("demandBands", c.demandBands, c.id);
    // Grid shape must match the band counts.
    if (c.grid.length !== c.ageBands.length) {
      throw new Error(
        `Bourbon card ${c.id}: grid has ${c.grid.length} rows but ageBands has ${c.ageBands.length} entries`,
      );
    }
    for (const row of c.grid) {
      if (row.length !== c.demandBands.length) {
        throw new Error(
          `Bourbon card ${c.id}: grid row length ${row.length} ≠ demandBands length ${c.demandBands.length}`,
        );
      }
    }
    if (c.recipe) {
      for (const k of Object.keys(c.recipe)) {
        if (!recipeKeys.has(k)) {
          throw new Error(
            `Bourbon card ${c.id} has unknown recipe key '${k}' (expected corn / barley / rye / wheat / grain)`,
          );
        }
      }
    }
    // Default brandValue for Gold-capable cards: grid maximum + a small
    // rarity bonus, rounded up to the nearest $5, with a $25 floor so a
    // trophy is always meaningful end-game scoring even after the
    // post-free-resources rebalance shrunk grid ceilings. Cards without
    // a Gold award never become trophies, so they don't get a brandValue.
    if (c.awards && c.awards.gold && typeof c.brandValue !== "number") {
      const gridMax = Math.max(...c.grid.flatMap((row) => row));
      const rarityBonus = c.rarity === "Rare" ? 10 : 5;
      const raw = gridMax + rarityBonus;
      const rounded = Math.ceil(raw / 5) * 5;
      c.brandValue = Math.max(rounded, 25);
    }
    if (!c.tier) c.tier = deriveTier(c);
    const [maxAge, maxDemand] = MAX_GRID_BY_TIER[c.tier];
    if (c.ageBands.length > maxAge || c.demandBands.length > maxDemand) {
      throw new Error(
        `Bourbon card ${c.id} (${c.tier}): grid ${c.ageBands.length}×${c.demandBands.length} exceeds tier max ${maxAge}×${maxDemand}`,
      );
    }
  }

  const body =
    `import type { BourbonCardDef } from "./types";\n\n` +
    `export const BOURBON_CARDS: readonly BourbonCardDef[] = ${JSON.stringify(cards, null, 2)} as const;\n\n` +
    `export const BOURBON_CARDS_BY_ID: Readonly<Record<string, BourbonCardDef>> = Object.freeze(\n` +
    `  Object.fromEntries(BOURBON_CARDS.map((c) => [c.id, c]))\n` +
    `);\n`;

  writeTs("bourbon.generated.ts", body);
}

// ---------- Investment cards ----------

function buildInvestment() {
  const doc = loadYaml("investment_catalog.yaml");
  const cards = doc.cards as Array<{
    id: string;
    name: string;
    rarity: string;
    capital: number;
    short: string;
    effect: string;
    deckCopies: number;
    modifiers: Array<Record<string, unknown>>;
  }>;

  for (const c of cards) {
    if (typeof c.capital !== "number") {
      throw new Error(`Investment ${c.id} missing capital`);
    }
    for (const m of c.modifiers ?? []) {
      const kind = m.kind as string;
      if (
        kind !== "rickhouse_fee_discount" &&
        kind !== "action_cost_discount" &&
        kind !== "market_buy_bonus_cards"
      ) {
        throw new Error(`Investment ${c.id} unknown modifier kind: ${kind}`);
      }
    }
  }

  const body =
    `import type { InvestmentCardDef } from "./types";\n\n` +
    `export const INVESTMENT_CARDS: readonly InvestmentCardDef[] = ${JSON.stringify(cards, null, 2)} as const;\n\n` +
    `export const INVESTMENT_CARDS_BY_ID: Readonly<Record<string, InvestmentCardDef>> = Object.freeze(\n` +
    `  Object.fromEntries(INVESTMENT_CARDS.map((c) => [c.id, c]))\n` +
    `);\n`;

  writeTs("investment.generated.ts", body);
}

// ---------- Operations cards ----------

function buildOperations() {
  const doc = loadYaml("operations_cards.yaml");
  const categories = doc.categories as Array<{
    id: string;
    title: string;
    cards: Array<{ id: string; title: string; concept: string; effect: string }>;
  }>;

  type Out = {
    id: string;
    categoryId: string;
    title: string;
    concept: string;
    effect: string;
  };
  const flat: Out[] = [];
  for (const cat of categories) {
    for (const c of cat.cards) {
      flat.push({
        id: c.id,
        categoryId: cat.id,
        title: c.title,
        concept: c.concept,
        effect: c.effect,
      });
    }
  }

  const body =
    `import type { OperationsCardDef } from "./types";\n\n` +
    `export const OPERATIONS_CARDS: readonly OperationsCardDef[] = ${JSON.stringify(flat, null, 2)} as const;\n\n` +
    `export const OPERATIONS_CARDS_BY_ID: Readonly<Record<string, OperationsCardDef>> = Object.freeze(\n` +
    `  Object.fromEntries(OPERATIONS_CARDS.map((c) => [c.id, c]))\n` +
    `);\n`;

  writeTs("operations.generated.ts", body);
}

// ---------- Resource cards (specialty) ----------

function buildResources() {
  const doc = loadYaml("resource_cards.yaml");
  const categories = doc.categories as Array<{
    id: string;
    title: string;
    cards: Array<{
      id: string;
      name: string;
      hook?: string;
      rule: string;
      play: Record<string, unknown>;
    }>;
  }>;

  type Out = {
    id: string;
    name: string;
    categoryId: string;
    hook?: string;
    rule: string;
    play: Record<string, unknown>;
  };
  const flat: Out[] = [];
  for (const cat of categories) {
    for (const c of cat.cards) {
      flat.push({
        id: c.id,
        name: c.name,
        categoryId: cat.id,
        hook: c.hook,
        rule: c.rule,
        play: c.play,
      });
    }
  }

  const body =
    `import type { ResourceCardDef } from "./types";\n\n` +
    `export const SPECIALTY_RESOURCES: readonly ResourceCardDef[] = ${JSON.stringify(flat, null, 2)} as unknown as readonly ResourceCardDef[];\n\n` +
    `export const SPECIALTY_RESOURCES_BY_ID: Readonly<Record<string, ResourceCardDef>> = Object.freeze(\n` +
    `  Object.fromEntries(SPECIALTY_RESOURCES.map((c) => [c.id, c]))\n` +
    `);\n`;

  writeTs("resource.generated.ts", body);
}

// ---------- Market cards ----------

function buildMarket() {
  const doc = loadYaml("market_cards.yaml");
  type Resolved =
    | { kind: "demand_delta"; delta: number }
    | {
        kind: "demand_delta_conditional";
        threshold: number;
        deltaAbove: number;
        deltaBelow: number;
      }
    | { kind: "persistent_demand_delta"; delta: number; extraRounds: number }
    | {
        kind: "conditional_demand_boost";
        delta: number;
        minAge?: number;
        topBandOnly?: boolean;
        firstSaleOnly?: boolean;
      }
    | { kind: "resource_shortage"; resource: string }
    | { kind: "rent_surcharge"; surcharge: number }
    | { kind: "accelerated_demand_decay"; perSale: number }
    | { kind: "leader_skip_make"; criterion: string }
    | { kind: "leader_discard_bill"; criterion: string }
    | { kind: "rickhouse_age_loss"; rickhouseId: string; loss: number }
    | { kind: "all_draw_bourbon"; count: number }
    | { kind: "all_draw_resource"; resource?: string; count: number }
    | { kind: "flavor" };

  const cards = doc.cards as Array<{
    id: string;
    title: string;
    effect: string;
    deckCopies: number;
    resolved: Resolved;
  }>;

  const knownKinds = new Set([
    "demand_delta",
    "demand_delta_conditional",
    "persistent_demand_delta",
    "conditional_demand_boost",
    "resource_shortage",
    "rent_surcharge",
    "accelerated_demand_decay",
    "leader_skip_make",
    "leader_discard_bill",
    "rickhouse_age_loss",
    "all_draw_bourbon",
    "all_draw_resource",
    "flavor",
  ]);
  for (const c of cards) {
    if (!c.id || !c.title) {
      throw new Error(`Market card missing id/title: ${JSON.stringify(c)}`);
    }
    if (!c.resolved || !knownKinds.has(c.resolved.kind)) {
      throw new Error(
        `Market card ${c.id} has unknown resolved.kind: ${c.resolved?.kind}`,
      );
    }
    if (typeof c.deckCopies !== "number" || c.deckCopies < 1) {
      throw new Error(`Market card ${c.id} needs deckCopies ≥ 1`);
    }
  }

  const body =
    `/**\n` +
    ` * AUTOGENERATED — DO NOT EDIT.\n` +
    ` * Source: data/market_cards.yaml. Run \`npm run build:catalogs\` to regenerate.\n` +
    ` */\n\n` +
    `import type { MarketCardDef } from "./types";\n\n` +
    `export const MARKET_CARDS: readonly MarketCardDef[] = ${JSON.stringify(cards, null, 2)} as const;\n\n` +
    `export const MARKET_CARDS_BY_ID: Readonly<Record<string, MarketCardDef>> = Object.freeze(\n` +
    `  Object.fromEntries(MARKET_CARDS.map((c) => [c.id, c] as const))\n` +
    `);\n`;

  writeTs("market.generated.ts", body);
}

// ---------- Distillery cards ----------

function buildDistilleries() {
  const doc = loadYaml("distillery_cards.yaml");
  type Bonus =
    | { kind: "cash"; amount: number }
    | { kind: "mash_bills"; count: number }
    | { kind: "resources"; cards: { resource: string; count: number }[] }
    | { kind: "operations"; count: number }
    | { kind: "peek_market"; count: number };
  type Perk =
    | { kind: "free_make_per_round" }
    | { kind: "barrel_age_bonus"; extra: number }
    | { kind: "solo_rickhouse_no_rent" }
    | { kind: "first_sale_no_demand_drop" }
    | { kind: "draw_two_keep_one_bourbon" }
    | { kind: "draw_replacement_on_ops" }
    | { kind: "paid_action_discount"; amount: number }
    | { kind: "free_cask_reuse_per_round" };
  const cards = doc.cards as Array<{
    id: string;
    name: string;
    flavor: string;
    bonus_text: string;
    perk_text: string;
    bonuses: Bonus[];
    perk: Perk;
  }>;

  const knownBonusKinds = new Set([
    "cash",
    "mash_bills",
    "resources",
    "operations",
    "peek_market",
  ]);
  const knownPerkKinds = new Set([
    "free_make_per_round",
    "barrel_age_bonus",
    "solo_rickhouse_no_rent",
    "first_sale_no_demand_drop",
    "draw_two_keep_one_bourbon",
    "draw_replacement_on_ops",
    "paid_action_discount",
    "free_cask_reuse_per_round",
  ]);
  const validResources = new Set(["cask", "corn", "barley", "rye", "wheat"]);
  const seenIds = new Set<string>();
  for (const c of cards) {
    if (!c.id || seenIds.has(c.id)) {
      throw new Error(`Distillery card has missing or duplicate id: ${c.id}`);
    }
    seenIds.add(c.id);
    if (!c.name || !c.flavor || !c.bonus_text || !c.perk_text) {
      throw new Error(`Distillery card ${c.id} missing one of name / flavor / bonus_text / perk_text`);
    }
    if (!Array.isArray(c.bonuses) || c.bonuses.length === 0) {
      throw new Error(`Distillery card ${c.id} must have ≥1 bonus`);
    }
    for (const b of c.bonuses) {
      if (!knownBonusKinds.has(b.kind)) {
        throw new Error(`Distillery card ${c.id} unknown bonus kind: ${b.kind}`);
      }
      if (b.kind === "resources") {
        for (const r of b.cards) {
          if (!validResources.has(r.resource)) {
            throw new Error(`Distillery card ${c.id} bonus has invalid resource: ${r.resource}`);
          }
          if (!(r.count > 0)) {
            throw new Error(`Distillery card ${c.id} resource bonus needs count > 0`);
          }
        }
      }
    }
    if (!c.perk || !knownPerkKinds.has(c.perk.kind)) {
      throw new Error(`Distillery card ${c.id} unknown perk kind: ${c.perk?.kind}`);
    }
  }

  const body =
    `import type { DistilleryCardDef } from "./types";\n\n` +
    `export const DISTILLERY_CARDS: readonly DistilleryCardDef[] = ${JSON.stringify(cards, null, 2)} as const;\n\n` +
    `export const DISTILLERY_CARDS_BY_ID: Readonly<Record<string, DistilleryCardDef>> = Object.freeze(\n` +
    `  Object.fromEntries(DISTILLERY_CARDS.map((c) => [c.id, c]))\n` +
    `);\n`;

  writeTs("distillery.generated.ts", body);
}

// ---------- Main ----------

buildBourbon();
buildInvestment();
buildOperations();
buildResources();
buildMarket();
buildDistilleries();

console.log("catalog build complete");
